---
title: "1. Data Cleaning"
author: "Kaidi Kang"
date: "2023-04-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Data
```{r}
setwd("~/RESI/longitudinal/data_analysis")
lifespan <- readr::read_csv("data/raw_data/lifespan_dataset_4Nov2022.csv")
lifespan %<>% as.data.frame
```

```{r}
# Data cleaning
lifespan$age_years = lifespan$age_days / 365
lifespan$subj_ID = paste0(lifespan$study, lifespan$participant)
lifespan$GMV_10000 = lifespan$GMV/10000
lifespan$sGMV_10000 = lifespan$sGMV/10000
lifespan$WMV_10000 = lifespan$WMV/10000
lifespan$Ventricles_10000 = lifespan$Ventricles/10000
lifespan$sex_01 = ifelse(lifespan$sex == "Male", 1, 0)
```


```{r}
var_list = c("GMV", "sGMV", "WMV", "participant", "study", "age_years", "sex", "sex_01", "dx", "site", "GMV_10000", "sGMV_10000", "WMV_10000" )
```

## Age distribution of CN subjects in each study

```{r, fig.height = 5, fig.width= 20}
lifespan_no_abcd = subset(lifespan, study != "ABCD")

cn_data = lifespan_no_abcd %>% subset(dx == "CN" & fs_version %in% c("FS6_T1", "FS6_T1T2") & run == 1 & !is.na(study))
# cn_data = lifespan %>% subset(dx == "CN" & fs_version %in% c("FS6_T1") & run == 1 & !is.na(study))

# sort the study by median age
median_age = cn_data %>% group_by(study) %>% summarise(med_age = median(age_years), range_age_lower = range(age_years)[1], range_age_upper = range(age_years)[2])
median_age = median_age[order(median_age$med_age), ]
median_age$index = 1:nrow(median_age)

cn_data$study %<>% factor(levels = median_age$study)

ggplot(cn_data, aes(x = study, y = age_years)) + geom_boxplot() + guides(x =  guide_axis(angle = 90)) + labs(title = "Age distribution in each study", y = "Age (in years)", x = "Study")
```

## Longitudinal ABCD data

```{r}
# read-in ABCD data
abcd_smri_tbss <- read_csv("data/raw_data/abcd_smri_tbss.csv") %>% as.data.frame()
abcd = abcd_smri_tbss[, c("src_subject_id.x", "interview_age.x", "sex.x", "eventname.x", "site", 
                          # brain volumes 
                          "smri_vol_scs_subcorticalgv", "smri_vol_scs_cbwmatterlh", "smri_vol_scs_cbwmatterrh", 
                          "smri_vol_scs_wholeb", "smri_vol_scs_allventricles")]

# read-in id
id_data = read_csv("data/raw_data/ABCD_info_forKaidi.csv") %>% as.data.frame()
id_data = id_data[order(id_data$participant),]
## merge with the long ABCD data
abcd = abcd[order(abcd$src_subject_id.x, abcd$interview_age.x), ]
abcd = merge(abcd, id_data, by.x = "src_subject_id.x", by.y = "participant", all.x = TRUE)

# cleaning the site values
abcd$site.x[abcd$src_subject_id.x == "NDAR_INVBKW33JVR"] = abcd$site.y[abcd$src_subject_id.x == "NDAR_INVBKW33JVR"]
abcd$site = abcd$site.x


abcd = abcd[order(abcd$src_subject_id.x, abcd$interview_age.x, decreasing = FALSE), ]

abcd$GMV = with(abcd, smri_vol_scs_wholeb - (smri_vol_scs_cbwmatterlh + smri_vol_scs_cbwmatterrh) - smri_vol_scs_allventricles - smri_vol_scs_subcorticalgv)

abcd$sGMV = abcd$smri_vol_scs_subcorticalgv
# abcd$sGMV %>% summary
abcd$WMV = with(abcd, smri_vol_scs_cbwmatterlh + smri_vol_scs_cbwmatterrh)
# abcd$WMV %>% summary

abcd$age_years = abcd$interview_age.x / 12
abcd$sex_01 = ifelse(abcd$sex.x == "M", 1, 0)
abcd$GMV_10000 = abcd$GMV / 10000
abcd$sGMV_10000 = abcd$sGMV / 10000
abcd$WMV_10000 = abcd$WMV / 10000



# generate a new "numeric" id
# Note: geeglm has problem with ID values containing characters
abcd %<>% group_by(src_subject_id.x) %>% mutate(temp_id = cur_group_id()) 

# data reformatting
abcd$participant = abcd$temp_id
abcd$study = "ABCD"
abcd$sex = ifelse(abcd$sex.x == "M", "Male", "Female")

abcd = abcd[, var_list]
cn_abcd = subset(abcd, dx == "CN")

# covert to `data.frame`
cn_abcd %<>% as.data.frame

```


Sample sizes: 
```{r}
cat("After restricting to CN subject, the dataset contains", nrow(cn_data) + nrow(cn_abcd), "observations from", (unique(paste0(cn_data$participant, cn_data$study)) %>% length) + (unique(cn_abcd$participant) %>% length), "subjects")
```


## Data after further data cleaning
```{r}
cn_data_clean = subset(cn_data, !(study == "ARWIBO" & participant == 17156 & session == 2 ))
# remove duplicated rows
cn_data_clean = subset(cn_data_clean, !duplicated(cn_data_clean))
# ADHD200
ADHD200 <- cn_data_clean %>% filter(study == "ADHD200") %>% group_by(study, participant) %>% slice_max(age_days)
cn_data_clean = rbind(subset(cn_data_clean, study != "ADHD200"), ADHD200)
# EDSD
cn_data_clean = subset(cn_data_clean, !(study == "EDSD" & session != 1))
# OASIS3
OASIS3 <- cn_data_clean %>% filter(study == "OASIS3") %>% group_by(study, participant) %>% slice_min(age_days)
cn_data_clean = rbind(subset(cn_data_clean, study != "OASIS3"), OASIS3)
# Oulu
cn_data_clean = subset(cn_data_clean, study != "Oulu")
# STRIVE
cn_data_clean = subset(cn_data_clean, study != "STRIVE")
# Cornell_C2
cn_data_clean = subset(cn_data_clean, study != "Cornell_C2")
# PPMI:
PPMI = cn_data_clean %>% filter(study == "PPMI") %>% group_by(study, participant) %>% slice_min(age_years)
cn_data_clean = rbind(subset(cn_data_clean, study != "PPMI"), PPMI)
# FemaleASD
FemaleASD = cn_data_clean %>% filter(study == "FemaleASD") %>% group_by(study, participant) %>% slice_min(age_years)
cn_data_clean = rbind(subset(cn_data_clean, study != "FemaleASD"), FemaleASD)
```

```{r}
# Adding ABCD to the analysis dataset
cn_data_clean = cn_data_clean[, var_list]
cn_data_clean = subset(cn_data_clean , study != "ABCD")
cn_data_clean = rbind(cn_data_clean[, var_list], cn_abcd[var_list])
```


**Sample sizes: **
```{r}
cat("After further data cleaning, the dataset contains", nrow(cn_data_clean), "observations from", (unique(paste0(cn_data_clean$participant, cn_data_clean$study)) %>% length), "subjects from", unique(cn_data_clean$study) %>% length, "studies") 
```


```{r}
# FUNCTION for creating study summary table
sum_tab = function(data) {
  # independent data
  ind_data = data %>% group_by(study, participant) %>% slice_sample(n = 1)
  # Note: there may be some subjects from different study but having same subject IDs.
  tab1 = ind_data %>% group_by(study) %>% summarize(N = length(unique(participant)))
  tab2 = data %>% group_by(study) %>% summarise(tot_obs = length(participant))
  tab = merge(tab1, tab2)
  tab = tab[order(tab$N, decreasing = TRUE),]
  rownames(tab) = as.character(1:nrow(tab))
  tab %<>% mutate(Design = ifelse(N == tot_obs, "Cross-sectional", "Longitudinal"))
  return(tab)
}
```

```{r, fig.height = 5, fig.width= 20}
# CREATING A STUDY INFORMATION SUMMARY TABLE
study_info_clean = sum_tab(cn_data_clean) 

# Only include studies with N >= 20
study_info_clean = subset(study_info_clean, N >= 20)

# calculating median, sd and range of age for each study
median_age = cn_data_clean %>% group_by(study) %>% summarise(med_age = median(age_years), 
                                                             mean_age = moment(age_years), 
                                                             m2_age = moment(age_years, order = 2, center = TRUE) %>% sqrt(), # (2nd central moment)^(1/2)
                                                             m3_age = moment(age_years, order = 3, center = TRUE) %>% nthroot(3), # (3rd central moment)^(1/3)
                                                             mean_sex = moment(sex_01),
                                                             m2_sex = moment(sex_01, order = 2, center = TRUE) %>% sqrt(),
                                                             m3_sex = moment(sex_01, order = 3, center = TRUE) %>% nthroot(3)
                                                             )

cn_data_clean %<>% group_by(study, participant) %>% mutate(#subj_age_dis = range(age_years)[2] - range(age_years)[1],
                                                            subj_num_obs = length(age_years))
                                                            # subj_mean_obs_dis = subj_age_dis/subj_num_obs)
# obs_distance = add_on %>% group_by(study) %>% summarise(mean_obs_dis = mean(subj_mean_obs_dis))

median_age = median_age[order(median_age$med_age), ]
# median_age$index = 1:nrow(median_age)

# adding median age and its range
study_info_clean = merge(study_info_clean, median_age)
# study_info_clean = merge(study_info_clean, obs_distance)
study_info_clean = study_info_clean[order(study_info_clean$med_age), ]
study_info_clean$index = 1:nrow(study_info_clean)
study_info_clean = study_info_clean[order(study_info_clean$Design, study_info_clean$m2_age), ]
study_info_clean$index_sd_age = 1:nrow(study_info_clean)
```


```{r, eval = FALSE}
write.csv(cn_data_clean, "data/analysis_data/cn_data_clean.csv")
write.csv(study_info_clean, "data/analysis_data/study_info_clean.csv")
```



