---
title: "3. Study-level Analysis"
author: "Kaidi Kang"
date: "2023-04-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Analyses 
```{r}
setwd("~/RESI/longitudinal/data_analysis")
source("Code/functions/resi_geeglm.R")
```


## Study-wise analyses

**Note:**

+ `geepack::geeglm` requires the data to be properly ordered by "time" with in each subject. Otherwise, the cluster variable may not be identified.

```{r}
analysis_data <- read_csv("data/analysis_data/analysis_data_combat.csv")
analysis_data %<>% as.data.frame # `tibble` will cause a lot of problems with current RESI package
study_info_clean <- read_csv("data/analysis_data/study_info_clean.csv")
study_info_clean %<>% as.data.frame
```

```{r}
# the models used for each study
study_info_clean$model = ifelse(study_info_clean$Design == "Longitudinal", "gee", "lm")

# the model specification for each study
for (i in study_info_clean$study){
  study_data = subset(analysis_data, study == i)
  # include_site = length(unique(study_data$site)) > 1 # if there are >= 2 sites in the data
  include_sex = length(unique(study_data$sex)) > 1 # if two genders are both included in the study
  
  formula1 = paste("~ ns(age_years, df = 2)", 
                 ifelse(include_sex, " + sex_01", "")
                 )
  formula2 = paste("~ ", ifelse(include_sex, "sex_01", ""), 
                 " + ns(age_years, df = 2)"
                 )
  
  study_info_clean$mod_spec_age[which(study_info_clean$study == i)] = formula2 # to deal with the current sequential ANOVA in resi.geeglm
  study_info_clean$mod_spec_sex[which(study_info_clean$study == i)] = formula1
}
# study_info_clean
```



```{r, eval = FALSE}
# study-wise analyses
set.seed(1213)
## the outcomes
outcome = c("GMV", "sGMV", "WMV")
for (a in outcome){
  y = paste0(a, "_10000_combat") # use the harmonized outcomes
  for (i in 48){ #1:nrow(study_info_clean)
    study_i = study_info_clean$study[i] %>% as.character()
    design_i = study_info_clean$Design[i]
    cat("Study:", as.character(study_i), "\n")
    cat("    outcome:", a, "\n")
    cat("    Model:", as.character(study_info_clean$model[i]), "\n")
    cat("    Design:", design_i, "\n")
    formula_age = as.formula(paste0(y, study_info_clean$mod_spec_age[i]))
    formula_sex = as.formula(paste0(y, study_info_clean$mod_spec_sex[i]))
    data_i = subset(analysis_data, study == study_i)
    data_i = data_i[order(data_i$participant, data_i$age_years),]

    if (design_i == "Longitudinal") {
      # for age effect
      fit_age = geeglm(formula_age, data = data_i, id = participant, corstr = "exchangeable")
      resi_obj_age = fit_age %>% resi_geeglm(nboot = 1000, store.boot = TRUE)
      boot_val = resi_obj_age$boot.results[, (ncol(resi_obj_age$boot.results)-3): ncol(resi_obj_age$boot.results)]
      resi_se =  apply(as.matrix(boot_val), MARGIN = 2, FUN = sd, na.rm = TRUE)
      resi_obj_age$anova = cbind(resi_obj_age$anova, `L-RESI_se` = resi_se[1:2], `CS-RESI_se` = resi_se[3:4])
      # for sex effect
      fit_sex = geeglm(formula_sex, data = data_i, id = participant, corstr = "exchangeable")
      resi_obj_sex = fit_sex %>% resi_geeglm(nboot = 1000, store.boot = TRUE)
      boot_val = resi_obj_sex$boot.results[, (ncol(resi_obj_sex$boot.results)-3): ncol(resi_obj_sex$boot.results)]
      resi_se =  apply(as.matrix(boot_val), MARGIN = 2, FUN = sd, na.rm = TRUE)
      resi_obj_sex$anova = cbind(resi_obj_sex$anova, `L-RESI_se` = resi_se[1:2], `CS-RESI_se` = resi_se[3:4])
      
      
      resi_obj = list(resi_obj_age = resi_obj_age$anova,
                      resi_obj_sex = resi_obj_sex$anova)
      
    } 
    if (design_i == "Cross-sectional") {
      fit = lm(formula_age, data = data_i)
      resi_obj = resi(fit, data = data_i, store.boot = TRUE, coefficients = FALSE)
      se = resi_obj$boot.results %>% apply(2, sd, na.rm = TRUE)
      resi_obj$anova = cbind(resi_obj$anova, RESI_se = se[-1])
    }
    
    study_name = gsub("-", "_", study_i)
    assign(paste0("RESI_", study_name), resi_obj)
    saveRDS(resi_obj, file = paste0("RESI_objects/", a, "/", a, "_RESI_", study_name, ".rds"))
  }
}

```

# forest plots
```{r}
source("Code/functions/forest_plot.R")
study_info_clean <- read_csv("data/analysis_data/study_info_clean.csv")
analysis_data <- read_csv("data/analysis_data/analysis_data_combat.csv")
```

```{r}
# GMV
ES_GMV = forest_plot(study_info = study_info_clean, outcome = "GMV", x_ul = 2)
# sGMV
ES_sGMV = forest_plot(study_info = study_info_clean, outcome = "sGMV", x_ul = 2)
# WMV
ES_WMV = forest_plot(study_info = study_info_clean, outcome = "WMV", x_ul = 2)
```

## RESI for age on each outcome by study

```{r, fig.width=30, fig.height=20}
ggarrange(ES_GMV$plot_age, ES_sGMV$plot_age, ES_WMV$plot_age, ES_GMV$age_dist, ncol = 4) %>% suppressWarnings()
```

## RESI for sex on each outcome by study

```{r, fig.width=30, fig.height=20}
ggarrange(ES_GMV$plot_sex, ES_sGMV$plot_sex, ES_WMV$plot_sex, ES_GMV$age_dist, ncol = 4) %>% suppressWarnings()
```

