---
title: "6. Resampling Schemes in UKB and ADNI"
author: "Kaidi Kang"
date: "2023-05-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = FALSE, warning = FALSE}
setwd("~/RESI/longitudinal/data_analysis")
analysis_data <- readr::read_csv("data/analysis_data/analysis_data_combat.csv")
```


# CS study (UKB)
```{r, eval = FALSE}
UKB = subset(analysis_data, study == "UKB") # CS study
UKB$age_centile = rank(UKB$age_years)/nrow(UKB)

resamp_func_ukb = function(data, samp_size, scheme){
  # scheme 0
  if (scheme == 0) boot_id = sample(data$participant, size = samp_size, replace = TRUE)
  # scheme 1
  if (scheme == 1) boot_id = sample(data$participant, size = samp_size, replace = TRUE, prob = data$resamp_prob_s1)
  # scheme 2
  if (scheme == 2) boot_id = sample(data$participant, size = samp_size, replace = TRUE, prob = data$resamp_prob_s2)
  
  boot_data = data[unlist(lapply(boot_id, function(x) which(x == data[, "participant"]))), ]
  
  boot_val_sd = sd(boot_data$age_years)
  boot_lm = lm(GMV_10000_combat ~ ns(age_years, 2) + sex_01, data = boot_data)
  boot_resi = boot_lm %>% RESI::resi_pe(data = boot_data)
  boot_val_resi = boot_resi$anova[1, 4]
  output = c(boot_val_sd, boot_val_resi)
  names(output) = c("sd", "resi")
  return(output)
}


set.seed(2023)
nboot = 1000
num.cores = 30
Ns = seq(100, 29000, by = 500)
schemes = 0:2
output = expand.grid(N = Ns, scheme = schemes)

output = cbind(output, 
               mean_RESI_age = NA, RESI_age_ll = NA, RESI_age_ul = NA, 
               mean_sd_age = NA, sd_age_ll = NA, sd_age_ul = NA
               )

# adding probability to those closer to age range limits
# s0: scheme 0 (randomly selecting)
# s1: scheme 1 (prob of being sampled: abs(percentile_age - 0.5))
UKB$resamp_prob_s1 = 2 * abs(UKB$age_centile - 0.5)
# s2: 
UKB$resamp_prob_s2 = 2 * (UKB$age_centile - 0.5)^2

boot_val_resi = boot_val_sd = NULL 

for (a in 1:nrow(output)) {
  samp_size = output$N[a]
  scheme = output$scheme[a]
  print(a)

  temp = simplify2array(
            mclapply(1:nboot, function(simInd, data, samp_size, scheme){
              rep = resamp_func_ukb(data = data, samp_size = samp_size, scheme = scheme)
              return(rep)
            },
            data = UKB,
            samp_size = samp_size,
            scheme = scheme,
            mc.cores = num.cores
            )) %>% t() %>% as.data.frame
  
  output$mean_RESI_age[a] = mean(temp$resi)
  output$RESI_age_ll[a] = quantile(temp$resi, probs = c(0.025))
  output$RESI_age_ul[a] = quantile(temp$resi, probs = c(0.975))
  output$mean_sd_age[a] = mean(temp$sd)
  output$sd_age_ll[a] = quantile(temp$sd, probs = c(0.025))
  output$sd_age_ul[a] = quantile(temp$sd, probs = c(0.975))  
}

output

saveRDS(output, paste0("resampling_schemes/ADNI_UKB/resamp_scheme_UKB.rds"))
```


```{r}
# at the actual sample size of UKB (for table S7)
analysis_data <- read_csv("data/analysis_data/analysis_data_combat.csv")
UKB = subset(analysis_data, study == "UKB") # CS study
UKB$age_centile = rank(UKB$age_years)/nrow(UKB)

resamp_func_ukb = function(data, samp_size, scheme){
  # scheme 0
  if (scheme == 0) boot_id = sample(data$participant, size = samp_size, replace = TRUE)
  # scheme 1
  if (scheme == 1) boot_id = sample(data$participant, size = samp_size, replace = TRUE, prob = data$resamp_prob_s1)
  # scheme 2
  if (scheme == 2) boot_id = sample(data$participant, size = samp_size, replace = TRUE, prob = data$resamp_prob_s2)
  
  boot_data = data[unlist(lapply(boot_id, function(x) which(x == data[, "participant"]))), ]
  
  boot_val_sd = sd(boot_data$age_years)
  boot_lm = lm(GMV_10000_combat ~ ns(age_years, 2) + sex_01, data = boot_data)
  boot_resi = boot_lm %>% RESI::resi_pe(data = boot_data)
  boot_val_resi = boot_resi$anova[1, 4]
  output = c(boot_val_sd, boot_val_resi)
  names(output) = c("sd", "resi")
  return(output)
}

set.seed(2023)
nboot = 1000
num.cores = 45
Ns = nrow(UKB)
schemes = 0:2
output = expand.grid(N = Ns, scheme = schemes)

output = cbind(output, 
               mean_RESI_age = NA, RESI_age_ll = NA, RESI_age_ul = NA, 
               mean_sd_age = NA, sd_age_ll = NA, sd_age_ul = NA
               )

# adding probability to those closer to age range limits
# s0: scheme 0 (randomly selecting)
# s1: scheme 1 (prob of being sampled: abs(percentile_age - 0.5))
UKB$resamp_prob_s1 = 2 * abs(UKB$age_centile - 0.5)
# s2: 
UKB$resamp_prob_s2 = 2 * (UKB$age_centile - 0.5)^2

boot_val_resi = boot_val_sd = NULL 

for (a in 1:nrow(output)) {
  samp_size = output$N[a]
  scheme = output$scheme[a]
  print(a)

  temp = simplify2array(
            mclapply(1:nboot, function(simInd, data, samp_size, scheme){
              rep = resamp_func_ukb(data = data, samp_size = samp_size, scheme = scheme)
              return(rep)
            },
            data = UKB,
            samp_size = samp_size,
            scheme = scheme,
            mc.cores = num.cores
            )) %>% t() %>% as.data.frame
  
  output$mean_RESI_age[a] = mean(temp$resi)
  output$RESI_age_ll[a] = quantile(temp$resi, probs = c(0.025))
  output$RESI_age_ul[a] = quantile(temp$resi, probs = c(0.975))
  output$mean_sd_age[a] = mean(temp$sd)
  output$sd_age_ll[a] = quantile(temp$sd, probs = c(0.025))
  output$sd_age_ul[a] = quantile(temp$sd, probs = c(0.975))  
}

output

saveRDS(output, paste0("resampling_schemes/ADNI_UKB/resamp_scheme_UKB_actual_N.rds"))
```


## Longitudinal Study (ADNI)

```{r}
resamp_scheme_func = function(data, bl_data, N, btwn_scheme, within_scheme){
  # between-subject resampling
  # scheme 0
  if (btwn_scheme == 0) boot_id = sample(bl_data$participant, size = N, replace = TRUE)
  # scheme 1
  if (btwn_scheme == 1) boot_id = sample(bl_data$participant, size = N, replace = TRUE, prob = bl_data$bl_resamp_prob_s1)
  # scheme 2
  if (btwn_scheme == 2) boot_id = sample(bl_data$participant, size = N, replace = TRUE, prob = bl_data$bl_resamp_prob_s2)
  
  # subject-level bootstrap
  boot_data0 = data[unlist(lapply(boot_id, function(x) which(x == data[, "participant"]))), ]
  
  # Assign new ID to the bootstrap data
  boot_data0$new_id = rep(1:length(boot_id),
                          times = unlist(lapply(boot_id, function(x) length(which(x==data[,"participant"]))))
  )
  
  # within-subject-level bootstrap
  
  # if (within_scheme == 999) boot_data = boot_data0 # no within-subject resampling
  
  if (within_scheme == 0) boot_data = do.call(rbind, 
                                              lapply(split(boot_data0, boot_data0$new_id), 
                                                     function(x) {x[sample(1:nrow(x), x$subj_num_obs[1], replace = TRUE), ]} #
                                              )
  )
  if (within_scheme == 1) boot_data = do.call(rbind, 
                                              lapply(split(boot_data0, boot_data0$new_id), 
                                                     function(x) {x[sample(1:nrow(x), x$subj_num_obs[1], replace = TRUE, prob = x$within_resamp_prob_s1), ]} 
                                              )
  )
  if (within_scheme == 2) boot_data = do.call(rbind, 
                                              lapply(split(boot_data0, boot_data0$new_id), 
                                                     function(x) {x[sample(1:nrow(x), x$subj_num_obs[1], replace = TRUE, prob = x$within_resamp_prob_s2), ]} 
                                              )
  )
  
  # sorting the data by id and age
  boot_data = boot_data[order(boot_data$new_id, boot_data$age_years), ]
  
  # calculate the between- & within-subject SD of age in the bootstrap data 
  # using a linear mixed effects model
  lme_fit = lmer(age_years ~ (1 | new_id), data = boot_data)
  ran_eff_var = VarCorr(lme_fit) %>% as.data.frame
  # between-subject mean age
  btwn_subj_mean_age = summary(lme_fit)$coefficients[1]
  # between-subject sd of age
  btwn_subj_sd_age = ran_eff_var$vcov[1] %>% sqrt()
  # within-subject sd of age
  within_subj_sd_age = ran_eff_var$vcov[2] %>% sqrt()
  
  
  # boot_val_sd[i] = sd(boot_data$age_years)
  # age effect (using the full observations from each subject)
  boot_gee = geeglm(GMV_10000_combat ~ sex_01 + ns(age_years, 2), data = boot_data, corstr = "exchangeable", id = new_id) 
  boot_resi = boot_gee %>% resi_pe_geeglm(data = boot_data)
  boot_val_cs_resi = boot_resi$anova[2, 'CS-RESI'] # this is type 1 sequential anova
  boot_val_long_resi = boot_resi$anova[2, 'L-RESI']
  
  
  # increase the number of observations by 50%:
  if (within_scheme == 0) boot_data_more = do.call(rbind, 
                                              lapply(split(boot_data0, boot_data0$new_id), 
                                                     function(x) {x[sample(1:nrow(x), x$subj_num_obs[1] * 2, replace = TRUE), ]} #
                                              )
  )
  if (within_scheme == 1) boot_data_more= do.call(rbind, 
                                              lapply(split(boot_data0, boot_data0$new_id), 
                                                     function(x) {x[sample(1:nrow(x), x$subj_num_obs[1] * 2, replace = TRUE, prob = x$within_resamp_prob_s1), ]} 
                                              )
  )
  if (within_scheme == 2) boot_data_more = do.call(rbind, 
                                              lapply(split(boot_data0, boot_data0$new_id), 
                                                     function(x) {x[sample(1:nrow(x), x$subj_num_obs[1] * 2, replace = TRUE, prob = x$within_resamp_prob_s2), ]} 
                                              )
  )
  
  # sorting the data by id and age
  boot_data_more = boot_data[order(boot_data$new_id, boot_data$age_years), ]
  
  lme_fit_more = lmer(age_years ~ (1 | new_id), data = boot_data_more)
  ran_eff_var_more = VarCorr(lme_fit_more) %>% as.data.frame
  # between-subject mean age
  btwn_subj_mean_age_more = summary(lme_fit_more)$coefficients[1]
  # between-subject sd of age
  btwn_subj_sd_age_more = ran_eff_var_more$vcov[1] %>% sqrt()
  # within-subject sd of age
  within_subj_sd_age_more = ran_eff_var_more$vcov[2] %>% sqrt()
  
  
  boot_gee_more = geeglm(GMV_10000_combat ~ sex_01 + ns(age_years, 2), data = boot_data_more, corstr = "exchangeable", id = new_id) 
  boot_resi_more = boot_gee_more %>% resi_pe_geeglm(data = boot_data_more)
  boot_val_cs_resi_more = boot_resi_more$anova[2, 'CS-RESI'] # this is type 1 sequential anova
  boot_val_long_resi_more = boot_resi_more$anova[2, 'L-RESI']
  
  
  # 2-observation bootstrap data (using the first and last observation from each subject)
  # boot_data_2obs = boot_data %>% arrange(age_years) %>% group_by(new_id) %>% slice(c(1,n()))
  # New: baseline and a random obs after that
  boot_data_1obs = boot_data %>% arrange(age_years) %>% group_by(new_id) %>% slice(c(1))
  boot_data_2nd_obs = boot_data %>% group_by(new_id) %>% slice(2:n())
  boot_data_2nd_obs %<>% arrange(age_years) %>% group_by(new_id) %>% slice_sample(n = 1)
  boot_data_2obs = rbind(boot_data_1obs, boot_data_2nd_obs)
  boot_data_2obs = boot_data_2obs[order(boot_data_2obs$new_id, boot_data_2obs$age_years),]
                                                                                   
  lme_fit_2obs = lmer(age_years ~ (1 | new_id), data = boot_data_2obs)
  ran_eff_var_2obs = VarCorr(lme_fit_2obs) %>% as.data.frame
  # between-subject mean age
  btwn_subj_mean_age_2obs = summary(lme_fit_2obs)$coefficients[1]
  # between-subject sd of age
  btwn_subj_sd_age_2obs = ran_eff_var_2obs$vcov[1] %>% sqrt()
  # within-subject sd of age
  within_subj_sd_age_2obs = ran_eff_var_2obs$vcov[2] %>% sqrt()
  
  
  boot_gee_2obs = geeglm(GMV_10000_combat ~ sex_01 + ns(age_years, 2), data = boot_data_2obs, corstr = "exchangeable", id = new_id) 
  boot_resi_2obs = boot_gee_2obs %>% resi_pe_geeglm(data = boot_data_2obs)
  boot_val_cs_resi_2obs = boot_resi_2obs$anova[2, 'CS-RESI'] # this is type 1 sequential anova
  boot_val_long_resi_2obs = boot_resi_2obs$anova[2, 'L-RESI']

  return(c(boot_val_cs_resi = boot_val_cs_resi,
          boot_val_long_resi = boot_val_long_resi,
          boot_btwn_subj_mean_age = btwn_subj_mean_age,
          boot_btwn_subj_sd_age = btwn_subj_sd_age,
          boot_within_subj_sd_age = within_subj_sd_age,
          
          boot_val_cs_resi_2obs = boot_val_cs_resi_2obs,
          boot_val_long_resi_2obs = boot_val_long_resi_2obs,
          boot_btwn_subj_mean_age_2obs = btwn_subj_mean_age_2obs,
          boot_btwn_subj_sd_age_2obs = btwn_subj_sd_age_2obs,
          boot_within_subj_sd_age_2obs = within_subj_sd_age_2obs,
          
          boot_val_cs_resi_more = boot_val_cs_resi_more,
          boot_val_long_resi_more = boot_val_long_resi_more,
          boot_btwn_subj_mean_age_more = btwn_subj_mean_age_more,
          boot_btwn_subj_sd_age_more = btwn_subj_sd_age_more,
          boot_within_subj_sd_age_more = within_subj_sd_age_more)
         )
}
```

```{r, eval = FALSE}
set.seed(2023)
Sys.time()
library(parallel)
analysis_data <- read_csv("data/analysis_data/analysis_data_combat.csv")
ADNI = subset(analysis_data, study == "ADNI")
ADNI = ADNI[order(ADNI$participant, ADNI$age_years), ]

# the change in age during followup
ADNI %<>% group_by(participant) %>% mutate(age_change = max(age_years) - min(age_years))

# baseline data
bl_ADNI = ADNI %>% group_by(participant) %>% slice_head(n = 1)
bl_ADNI$bl_age_centile = rank(bl_ADNI$age_years)/nrow(bl_ADNI)
bl_ADNI$change_age_centile = rank(abs(bl_ADNI$age_change))/nrow(bl_ADNI)

# between-subject-level resampling probabilities (based on baseline age)
bl_ADNI$bl_resamp_prob_s1 = with(bl_ADNI, 2 * abs(bl_age_centile - 0.5))
bl_ADNI$bl_resamp_prob_s2 = with(bl_ADNI, 2 * (bl_age_centile - 0.5)^2)


# within-subject resampling probabilities
ADNI %<>% group_by(participant) %>% mutate(within_subj_age_centile = rank(age_years)/subj_num_obs,
                                           within_resamp_prob_s1 = 2 * abs(within_subj_age_centile - 0.5),
                                           within_resamp_prob_s2 = 2 * (within_subj_age_centile - 0.5)^2)


ADNI %<>% as.data.frame
# plot(resamp_prob_s1 ~ bl_age_centile, data = bl_ADNI)
# plot(resamp_prob_s2 ~ bl_age_centile, data = bl_ADNI)

Ns = seq(50, 3000, by = 100)
# between-subject resampling scheme.
btwn_schemes = 0:2
# with-in subject resampling scheme
within_schemes = c(0:2)

output = expand.grid(N = Ns, btwn_scheme = btwn_schemes, within_scheme = within_schemes)

output = cbind(output, 
               mean_CS_RESI_age = NA, CS_RESI_age_ll = NA, CS_RESI_age_ul = NA, 
               mean_long_RESI_age = NA, long_RESI_age_ll = NA, long_RESI_age_ul = NA,
               mean_mean_age = NA, mean_age_ll = NA, mean_age_ul = NA,
               mean_btwn_sd_age = NA, btwn_sd_age_ll = NA, btwn_sd_age_ul = NA,
               mean_within_sd_age = NA, within_sd_age_ll = NA, within_sd_age_ul = NA,
               
               mean_CS_RESI_age_2obs = NA, CS_RESI_age_2obs_ll = NA, CS_RESI_age_2obs_ul = NA,
               mean_long_RESI_age_2obs = NA, long_RESI_age_2obs_ll = NA, long_RESI_age_2obs_ul = NA,
               mean_mean_age_2obs = NA, mean_age_2obs_ll = NA, mean_age_2obs_ul = NA,
               mean_btwn_sd_age_2obs = NA, btwn_sd_age_2obs_ll = NA, btwn_sd_age_2obs_ul = NA,
               mean_within_sd_age_2obs = NA, within_sd_age_2obs_ll = NA, within_sd_age_2obs_ul = NA,
               
               mean_CS_RESI_age_more = NA, CS_RESI_age_more_ll = NA, CS_RESI_age_more_ul = NA,
               mean_long_RESI_age_more = NA, long_RESI_age_more_ll = NA, long_RESI_age_more_ul = NA,
               mean_mean_age_more = NA, mean_age_more_ll = NA, mean_age_more_ul = NA,
               mean_btwn_sd_age_more = NA, btwn_sd_age_more_ll = NA, btwn_sd_age_more_ul = NA,
               mean_within_sd_age_more = NA, within_sd_age_more_ll = NA, within_sd_age_more_ul = NA
               )

nsim = 1000
num.cores = 40
for (i in 1:nrow(output)){
  print(i)
  samp_size = output$N[i]
  btwn_s = output$btwn_scheme[i]
  within_s = output$within_scheme[i]
  
  temp <- simplify2array(
    mclapply(1:nsim, function(simInd, data, bl_data, N, btwn_scheme, within_scheme){
      rep = resamp_scheme_func(data = data, bl_data = bl_data, N = N, btwn_scheme = btwn_scheme, within_scheme = within_scheme)
      return(rep)
    },
    data = ADNI,
    bl_data = bl_ADNI,
    N = samp_size,
    btwn_scheme = btwn_s,
    within_scheme = within_s,
    mc.cores = num.cores
    )) %>% t()
  
  # mean
  output[which(output$N == samp_size & output$btwn_scheme == btwn_s & output$within_scheme == within_s), 
         c("mean_CS_RESI_age", "mean_long_RESI_age", "mean_mean_age", "mean_btwn_sd_age", "mean_within_sd_age", 
           "mean_CS_RESI_age_2obs", "mean_long_RESI_age_2obs", "mean_mean_age_2obs", "mean_btwn_sd_age_2obs", "mean_within_sd_age_2obs",
           "mean_CS_RESI_age_more", "mean_long_RESI_age_more", "mean_mean_age_more", "mean_btwn_sd_age_more", "mean_within_sd_age_more")] = colMeans(temp)
  
  # lower bound
  output[which(output$N == samp_size & output$btwn_scheme == btwn_s & output$within_scheme == within_s), 
       c("CS_RESI_age_ll", "long_RESI_age_ll", "mean_age_ll", "btwn_sd_age_ll", "within_sd_age_ll", 
         "CS_RESI_age_2obs_ll", "long_RESI_age_2obs_ll", "mean_age_2obs_ll", "btwn_sd_age_2obs_ll", "within_sd_age_2obs_ll",
         "CS_RESI_age_more_ll", "long_RESI_age_more_ll", "mean_age_more_ll", "btwn_sd_age_more_ll", "within_sd_age_more_ll")] =  apply(temp, 2, quantile, probs = c(0.025))
  
  # upper bound
  output[which(output$N == samp_size & output$btwn_scheme == btwn_s & output$within_scheme == within_s), 
       c("CS_RESI_age_ul", "long_RESI_age_ul", "mean_age_ul", "btwn_sd_age_ul", "within_sd_age_ul", 
         "CS_RESI_age_2obs_ul", "long_RESI_age_2obs_ul", "mean_age_2obs_ul", "btwn_sd_age_2obs_ul", "within_sd_age_2obs_ul",
         "CS_RESI_age_more_ul", "long_RESI_age_more_ul", "mean_age_more_ul", "btwn_sd_age_more_ul", "within_sd_age_more_ul")] =  apply(temp, 2, quantile, probs = c(0.975))

}
saveRDS(output, paste0("resampling_schemes/ADNI_UKB/resamp_scheme_ADNI_21Apr2023.rds"))
Sys.time()
```

```{r, eval = FALSE}
# At the actual sample size (for Tab S8)
set.seed(2023)
Sys.time()
library(parallel)
analysis_data <- read_csv("data/analysis_data/analysis_data_combat.csv")
ADNI = subset(analysis_data, study == "ADNI")
ADNI = ADNI[order(ADNI$participant, ADNI$age_years), ]

# the change in age during followup
ADNI %<>% group_by(participant) %>% mutate(age_change = max(age_years) - min(age_years))

# baseline data
bl_ADNI = ADNI %>% group_by(participant) %>% slice_head(n = 1)
bl_ADNI$bl_age_centile = rank(bl_ADNI$age_years)/nrow(bl_ADNI)
bl_ADNI$change_age_centile = rank(abs(bl_ADNI$age_change))/nrow(bl_ADNI)

# between-subject-level resampling probabilities (based on baseline age)
bl_ADNI$bl_resamp_prob_s1 = with(bl_ADNI, 2 * abs(bl_age_centile - 0.5))
bl_ADNI$bl_resamp_prob_s2 = with(bl_ADNI, 2 * (bl_age_centile - 0.5)^2)


# within-subject resampling probabilities
ADNI %<>% group_by(participant) %>% mutate(within_subj_age_centile = rank(age_years)/subj_num_obs,
                                           within_resamp_prob_s1 = 2 * abs(within_subj_age_centile - 0.5),
                                           within_resamp_prob_s2 = 2 * (within_subj_age_centile - 0.5)^2)


ADNI %<>% as.data.frame
# plot(resamp_prob_s1 ~ bl_age_centile, data = bl_ADNI)
# plot(resamp_prob_s2 ~ bl_age_centile, data = bl_ADNI)

Ns = length(unique(ADNI$participant))
# between-subject resampling scheme.
btwn_schemes = 0:2
# with-in subject resampling scheme
within_schemes = c(0:2)

output = expand.grid(N = Ns, btwn_scheme = btwn_schemes, within_scheme = within_schemes)

output = cbind(output, 
               mean_CS_RESI_age = NA, CS_RESI_age_ll = NA, CS_RESI_age_ul = NA, 
               mean_long_RESI_age = NA, long_RESI_age_ll = NA, long_RESI_age_ul = NA,
               mean_mean_age = NA, mean_age_ll = NA, mean_age_ul = NA,
               mean_btwn_sd_age = NA, btwn_sd_age_ll = NA, btwn_sd_age_ul = NA,
               mean_within_sd_age = NA, within_sd_age_ll = NA, within_sd_age_ul = NA,
               
               mean_CS_RESI_age_2obs = NA, CS_RESI_age_2obs_ll = NA, CS_RESI_age_2obs_ul = NA,
               mean_long_RESI_age_2obs = NA, long_RESI_age_2obs_ll = NA, long_RESI_age_2obs_ul = NA,
               mean_mean_age_2obs = NA, mean_age_2obs_ll = NA, mean_age_2obs_ul = NA,
               mean_btwn_sd_age_2obs = NA, btwn_sd_age_2obs_ll = NA, btwn_sd_age_2obs_ul = NA,
               mean_within_sd_age_2obs = NA, within_sd_age_2obs_ll = NA, within_sd_age_2obs_ul = NA,
               
               mean_CS_RESI_age_more = NA, CS_RESI_age_more_ll = NA, CS_RESI_age_more_ul = NA,
               mean_long_RESI_age_more = NA, long_RESI_age_more_ll = NA, long_RESI_age_more_ul = NA,
               mean_mean_age_more = NA, mean_age_more_ll = NA, mean_age_more_ul = NA,
               mean_btwn_sd_age_more = NA, btwn_sd_age_more_ll = NA, btwn_sd_age_more_ul = NA,
               mean_within_sd_age_more = NA, within_sd_age_more_ll = NA, within_sd_age_more_ul = NA
               )

nsim = 1000
num.cores = 45
for (i in 1:nrow(output)){
  print(i)
  samp_size = output$N[i]
  btwn_s = output$btwn_scheme[i]
  within_s = output$within_scheme[i]
  
  temp <- simplify2array(
    mclapply(1:nsim, function(simInd, data, bl_data, N, btwn_scheme, within_scheme){
      rep = resamp_scheme_func(data = data, bl_data = bl_data, N = N, btwn_scheme = btwn_scheme, within_scheme = within_scheme)
      return(rep)
    },
    data = ADNI,
    bl_data = bl_ADNI,
    N = samp_size,
    btwn_scheme = btwn_s,
    within_scheme = within_s,
    mc.cores = num.cores
    )) %>% t()
  
  # mean
  output[which(output$N == samp_size & output$btwn_scheme == btwn_s & output$within_scheme == within_s), 
         c("mean_CS_RESI_age", "mean_long_RESI_age", "mean_mean_age", "mean_btwn_sd_age", "mean_within_sd_age", 
           "mean_CS_RESI_age_2obs", "mean_long_RESI_age_2obs", "mean_mean_age_2obs", "mean_btwn_sd_age_2obs", "mean_within_sd_age_2obs",
           "mean_CS_RESI_age_more", "mean_long_RESI_age_more", "mean_mean_age_more", "mean_btwn_sd_age_more", "mean_within_sd_age_more")] = colMeans(temp)
  
  # lower bound
  output[which(output$N == samp_size & output$btwn_scheme == btwn_s & output$within_scheme == within_s), 
       c("CS_RESI_age_ll", "long_RESI_age_ll", "mean_age_ll", "btwn_sd_age_ll", "within_sd_age_ll", 
         "CS_RESI_age_2obs_ll", "long_RESI_age_2obs_ll", "mean_age_2obs_ll", "btwn_sd_age_2obs_ll", "within_sd_age_2obs_ll",
         "CS_RESI_age_more_ll", "long_RESI_age_more_ll", "mean_age_more_ll", "btwn_sd_age_more_ll", "within_sd_age_more_ll")] =  apply(temp, 2, quantile, probs = c(0.025))
  
  # upper bound
  output[which(output$N == samp_size & output$btwn_scheme == btwn_s & output$within_scheme == within_s), 
       c("CS_RESI_age_ul", "long_RESI_age_ul", "mean_age_ul", "btwn_sd_age_ul", "within_sd_age_ul", 
         "CS_RESI_age_2obs_ul", "long_RESI_age_2obs_ul", "mean_age_2obs_ul", "btwn_sd_age_2obs_ul", "within_sd_age_2obs_ul",
         "CS_RESI_age_more_ul", "long_RESI_age_more_ul", "mean_age_more_ul", "btwn_sd_age_more_ul", "within_sd_age_more_ul")] =  apply(temp, 2, quantile, probs = c(0.975))

}
saveRDS(output, paste0("resampling_schemes/ADNI_UKB/resamp_scheme_ADNI_21Apr2023_actual_N.rds"))
Sys.time()
```


## Results

### Fig. 3

```{r, fig.height=3, fig.width=12}
# UKB
output <- readRDS("resampling_schemes/ADNI_UKB/resamp_scheme_UKB.rds")
output$scheme %<>% as.factor
# increase ES
p1 = ggplot(data = output, aes(x = N, y = mean_RESI_age, color = scheme, group = scheme)) +  
    geom_ribbon(aes(ymin = RESI_age_ll, ymax = RESI_age_ul, fill = scheme), alpha=0.2, linetype = 0) + 
    geom_line(size = 1) + # scale_color_viridis_d(aesthetics = c("colour", "fill"), begin = 0.1, end = 0.95, option = 'viridis') + 
  theme_classic() + labs(title = "", y = 'RESI for age', x = 'Sample size') + theme(legend.position = "none") + theme(axis.text.x = element_text(angle = 45, vjust = 0.5)) 

# sampling probabilities
scheme0 = data.frame(perc = seq(0, 1, by = 0.01), scheme = "Scheme 0", prob = 1) 
scheme1 = data.frame(perc = seq(0, 1, by = 0.01), scheme = "Scheme 1")
scheme1$prob = 2*abs(scheme1$perc - 0.5) 
scheme2 = data.frame(perc = seq(0, 1, by = 0.01), scheme = "Scheme 2")
scheme2$prob = 2*(scheme2$perc - 0.5)^2 / 0.5
data_plot = rbind(scheme0, scheme1, scheme2)

p2 = ggplot(data = data_plot, aes(x = perc, y = prob, color = scheme, group = scheme)) +  
    geom_line(size = 1) + # scale_color_viridis_d(aesthetics = c("colour"), begin = 0.1, end = 0.95, option = 'viridis') + 
  theme_classic() + labs(title = "", y = 'Relative probability', x = 'Age percentile') 

legend = get_legend(p2)

p2 = ggplot(data = data_plot, aes(x = perc, y = prob, color = scheme, group = scheme)) +  
    geom_line(size = 1) + # scale_color_viridis_d(aesthetics = c("colour"), begin = 0.1, end = 0.95, option = 'viridis') + 
  theme_classic() + labs(title = "Study: UKB", y = 'Relative probability', x = 'Age percentile') + theme(legend.position = "none")     


# resampled sd of age
p3 = ggplot(data = output, aes(x = N, y = mean_sd_age, color = scheme, group = scheme)) +  
    geom_ribbon(aes(ymin = sd_age_ll, ymax = sd_age_ul, fill = scheme), alpha=0.2, linetype = 0) + 
    geom_line(size = 1) + # scale_color_viridis_d(aesthetics = c("colour", "fill"), begin = 0.1, end = 0.95, option = 'viridis') + 
  theme_classic() + labs(title = "", y = 'SD of age', x = 'Sample size') + theme(legend.position = "none") + theme(axis.text.x = element_text(angle = 45, vjust = 0.5))     


P_UKB = plot_grid(NULL, p2, p3, p1, NULL,  labels = c("", "(A)", "(B)", "(C)", ""), rel_widths = c(0.25, 1, 1, 1, 0.25), nrow = 1) # %>% suppressWarnings()

```

```{r, fig.height = 10, fig.width=8}
# Resampling in ADNI
output <- readRDS("resampling_schemes/ADNI_UKB/resamp_scheme_ADNI_21Apr2023.rds")
output = subset(output, within_scheme != 999)
# reset upper limit
output$long_RESI_age_ul = ifelse(output$long_RESI_age_ul > 1.2, 1.2, output$long_RESI_age_ul)
output$CS_RESI_age_ul = ifelse(output$CS_RESI_age_ul > 1.2, 1.2, output$CS_RESI_age_ul)

output$`Within-subject Resampling Scheme` = factor(output$within_scheme, labels = c("Scheme 0", "Scheme 1", "Scheme 2"))
output$`Baseline Resampling Scheme` = factor(output$btwn_scheme, labels = c("Scheme 0", "Scheme 1", "Scheme 2"))


p1 = ggplot(data = output, aes(x = N, y = mean_CS_RESI_age, color = `Baseline Resampling Scheme`, group = `Baseline Resampling Scheme`)) + 
  geom_ribbon(aes(ymin = CS_RESI_age_ll, ymax = CS_RESI_age_ul, fill = `Baseline Resampling Scheme`), alpha=0.2, linetype = 0) +
  geom_line(size = 1) + 
  facet_wrap(~ `Within-subject Resampling Scheme`) + theme_bw() + theme(legend.position = "none") + theme(axis.text.x = element_text(angle = 45, vjust = 0.5))+ ylim(0, 1.25) + 
  labs(title = "Study: ADNI", y = 'CS-RESI', x = 'Sample size') 

  
p2 = ggplot(data = output, aes(x = N, y = mean_long_RESI_age, color = `Baseline Resampling Scheme`, group = `Baseline Resampling Scheme`)) + 
  geom_ribbon(aes(ymin = long_RESI_age_ll, ymax = long_RESI_age_ul, fill = `Baseline Resampling Scheme`), alpha=0.2, linetype = 0) +
  geom_line(size = 1) + facet_wrap(~ `Within-subject Resampling Scheme`) + labs(fill= "Baseline Resampling Scheme") + theme_bw() + theme(legend.position = "bottom") + 
  labs(title = "", y = 'L-RESI', x = 'Sample size') + ylim(0, 1.25)
legend = get_legend(p2)
p2 = ggplot(data = output, aes(x = N, y = mean_long_RESI_age, color = `Baseline Resampling Scheme`, group = `Baseline Resampling Scheme`)) + 
  geom_ribbon(aes(ymin = long_RESI_age_ll, ymax = long_RESI_age_ul, fill = `Baseline Resampling Scheme`), alpha=0.2, linetype = 0) +
  geom_line(size = 1) + facet_wrap(~ `Within-subject Resampling Scheme`) + labs(fill= "Baseline Resampling Scheme") + theme_bw() +   
  theme(legend.position = "none") + theme(axis.text.x = element_text(angle = 45, vjust = 0.5)) + 
  labs(title = "", y = 'L-RESI', x = 'Sample size') + ylim(0, 1.25)


P2 = plot_grid(p1, p2, 
               labels = "(D)",
               ncol = 1, rel_heights = c(1, 1)) %>% suppressWarnings()

# ggarrange(P1, P2, ncol = 1, heights = c(0.7, 2))

```


```{r, fig.height = 9, fig.width=10}
# two-obs resampling in ADNI

output$long_RESI_age_2obs_ul = ifelse(output$long_RESI_age_2obs_ul > 1.2, 1.2, output$long_RESI_age_2obs_ul)
output$CS_RESI_age_2obs_ul = ifelse(output$CS_RESI_age_2obs_ul > 1.2, 1.2, output$CS_RESI_age_2obs_ul)

p1 = ggplot(data = output, aes(x = N, y = mean_CS_RESI_age, color = `Baseline Resampling Scheme`, group = `Baseline Resampling Scheme`)) + 
  geom_ribbon(aes(ymin = CS_RESI_age_2obs_ll, ymax = CS_RESI_age_2obs_ul, fill = `Baseline Resampling Scheme`), alpha=0.2, linetype = 0) +
  geom_line(size = 1) + 
  facet_wrap(~ `Within-subject Resampling Scheme`) + theme_bw() + theme(legend.position = "none") + theme(axis.text.x = element_text(angle = 45, vjust = 0.5)) + ylim(0, 1.25) + 
  labs(title = "Study: ADNI (2-observation)", y = 'CS-RESI', x = 'Sample size') 


p2 = ggplot(data = output, aes(x = N, y = mean_long_RESI_age_2obs, color = `Baseline Resampling Scheme`, group = `Baseline Resampling Scheme`)) + 
  geom_ribbon(aes(ymin = long_RESI_age_2obs_ll, ymax = long_RESI_age_2obs_ul, fill = `Baseline Resampling Scheme`), alpha=0.2, linetype = 0) +
  geom_line(size = 1) + facet_wrap(~ `Within-subject Resampling Scheme`) + labs(fill= "Baseline Resampling Scheme") + theme_bw() +   
  theme(legend.position = "none") + theme(axis.text.x = element_text(angle = 45, vjust = 0.5)) + 
  labs(title = "", y = 'L-RESI', x = 'Sample size') + ylim(0, 1.25)

P3 = plot_grid(p1, p2,  labels = c("(E)"), rel_heights = c(1, 1), ncol = 1)


P_ADNI = plot_grid(P2, P3, rel_widths = c(1, 1), nrow = 1)
```


```{r, fig.height = 9, fig.width=10}
ggarrange(P_UKB, legend, P_ADNI, ncol = 1, heights = c(1, 0.2, 2))
```

### Fig S5. Between and within-subject SD of age in ADNI after resampling.
```{r, fig.height = 6, fig.width = 10}
# analysis_data <- read_csv("data/analysis_data/analysis_data_combat.csv")
# analysis_data %<>% as.data.frame # `tibble` will cause a lot of problems with current RESI package

output <- readRDS("resampling_schemes/ADNI_UKB/resamp_scheme_ADNI_21Apr2023.rds")

output$`Within-subject Resampling Scheme` = factor(output$within_scheme, labels = c("Scheme 0", "Scheme 1", "Scheme 2"))
output$`Baseline Resampling Scheme` = factor(output$btwn_scheme, labels = c("Scheme 0", "Scheme 1", "Scheme 2"))

# change of between-subject sd of age
p1 = ggplot(data = output, aes(x = N, y = mean_btwn_sd_age, color = `Baseline Resampling Scheme`, group = `Baseline Resampling Scheme`)) + 
  geom_ribbon(aes(ymin = btwn_sd_age_ll, ymax = btwn_sd_age_ul, fill = `Baseline Resampling Scheme`), alpha=0.2, linetype = 0) +
  geom_line(size = 1) + 
  facet_wrap(~ `Within-subject Resampling Scheme`) + theme_bw() + theme(legend.position = "none")  + 
  labs(title = " Study: ADNI", y = 'Between-subject SD of age', x = 'Sample size')


# change of within-subject sd of age
p2 = ggplot(data = output, aes(x = N, y = mean_within_sd_age, color = `Baseline Resampling Scheme`, group = `Baseline Resampling Scheme`)) + 
  geom_ribbon(aes(ymin = within_sd_age_ll, ymax = within_sd_age_ul, fill = `Baseline Resampling Scheme`), alpha=0.2, linetype = 0) +
  geom_line(size = 1) + 
  facet_wrap(~ `Within-subject Resampling Scheme`) + theme(legend.position = "bottom")  + 
  labs(title = "Study: ADNI", y = 'Within-subject SD of age', x = 'Sample size')
legend = get_legend(p2)
p2 = ggplot(data = output, aes(x = N, y = mean_within_sd_age, color = `Baseline Resampling Scheme`, group = `Baseline Resampling Scheme`)) + 
  geom_ribbon(aes(ymin = within_sd_age_ll, ymax = within_sd_age_ul, fill = `Baseline Resampling Scheme`), alpha=0.2, linetype = 0) +
  geom_line(size = 1) + 
  facet_wrap(~ `Within-subject Resampling Scheme`) + theme_bw() + theme(legend.position = "none")  + ylim(1, 5) +
  labs(title = " ", y = 'Within-subject SD of age', x = 'Sample size')

P1 = plot_grid(p1, p2, labels = c("(A)", ""), rel_heights = c(1, 1), ncol = 1)

# two-obs
p1 = ggplot(data = output, aes(x = N, y = mean_btwn_sd_age_2obs, color = `Baseline Resampling Scheme`, group = `Baseline Resampling Scheme`)) + 
  geom_ribbon(aes(ymin = btwn_sd_age_2obs_ll, ymax = btwn_sd_age_2obs_ul, fill = `Baseline Resampling Scheme`), alpha=0.2, linetype = 0) +
  geom_line(size = 1) + 
  facet_wrap(~ `Within-subject Resampling Scheme`) + theme_bw() + theme(legend.position = "none")  + 
  labs(title = " Study: ADNI (2-observation)", y = 'Between-subject SD of age', x = 'Sample size')


# change of within-subject sd of age
p2 = ggplot(data = output, aes(x = N, y = mean_within_sd_age_2obs, color = `Baseline Resampling Scheme`, group = `Baseline Resampling Scheme`)) + 
  geom_ribbon(aes(ymin = within_sd_age_2obs_ll, ymax = within_sd_age_2obs_ul, fill = `Baseline Resampling Scheme`), alpha=0.2, linetype = 0) +
  geom_line(size = 1) + 
  facet_wrap(~ `Within-subject Resampling Scheme`) + theme(legend.position = "bottom")  + 
  labs(title = "", y = 'Within-subject SD of age', x = 'Sample size')
legend = get_legend(p2)
p2 = ggplot(data = output, aes(x = N, y = mean_within_sd_age_2obs, color = `Baseline Resampling Scheme`, group = `Baseline Resampling Scheme`)) + 
  geom_ribbon(aes(ymin = within_sd_age_2obs_ll, ymax = within_sd_age_2obs_ul, fill = `Baseline Resampling Scheme`), alpha=0.2, linetype = 0) +
  geom_line(size = 1) + 
  facet_wrap(~ `Within-subject Resampling Scheme`) + theme_bw() + theme(legend.position = "none")  + ylim(1, 5) +
  labs(title = " ", y = 'Within-subject SD of age', x = 'Sample size')

P2 = plot_grid(p1, p2, labels = c("(B)", ""), rel_heights = c(1, 1), ncol = 1)

P3 = plot_grid(P1, P2, nrow = 1)

P4 = plot_grid(P3, legend, ncol = 1, rel_heights = c(1, 0.1))
P4
```
