---
title: "7. Resampling on Cognitive Variables in ABCD"
author: "Kaidi Kang"
date: "2023-05-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = FALSE, warning = FALSE}
setwd("~/RESI/longitudinal/data_analysis")
source("Code/functions/resi_geeglm.R")
```


# Data preparation
```{r, message = FALSE, warning = FALSE, eval = FALSE}
# read-in data
abcd_smri_tbss <- read_csv("data/raw_data/abcd_smri_tbss.csv") %>% as.data.frame()
abcd = abcd_smri_tbss[, c("src_subject_id.x", "interview_age.x", "sex.x", "eventname.x", "site", 
                          # PSYCHOMETRIC VARIABLES
                          "nihtbx_picvocab_fc", # NIH Toolbox Picture Vocabulary Test Age 3+ v2.0
                          "nihtbx_flanker_fc", # NIH Toolbox Flanker Inhibitory Control and Attention Test Ages 8-11 v2.0
                          "nihtbx_list_fc", # List Sorting Working Memory Test Age 7+ v2.0
                          "nihtbx_cardsort_fc", # Dimensional Change Card Sort Test Ages 8-11 v2.0 
                          "nihtbx_pattern_fc",  # Pattern Comparison Processing Speed Test Age 7
                          "nihtbx_picture_fc", # Picture Sequence Memory Test Age 8+ Form A
                          "nihtbx_reading_fc", # Oral Reading Recognition Test Age 3+
                          "nihtbx_fluidcomp_fc", # Cognition Fluid Composite
                          "nihtbx_cryst_fc", # Crystallized Composite
                          "nihtbx_totalcomp_fc", # Cognition Total Composite Score
                          # brain volumes 
                          "smri_vol_scs_subcorticalgv", "smri_vol_scs_cbwmatterlh", "smri_vol_scs_cbwmatterrh", 
                          "smri_vol_scs_wholeb", "smri_vol_scs_allventricles")]

# read-in ID and dx
id_data = read_csv("data/raw_data/ABCD_info_forKaidi.csv") %>% as.data.frame()
id_data = id_data[order(id_data$participant),]
## merge with the long ABCD data
abcd = abcd[order(abcd$src_subject_id.x, abcd$interview_age.x), ]
abcd = merge(abcd, id_data, by.x = "src_subject_id.x", by.y = "participant", all.x = TRUE)

# cleaning the site values
abcd$site.x[abcd$src_subject_id.x == "NDAR_INVBKW33JVR"] = abcd$site.y[abcd$src_subject_id.x == "NDAR_INVBKW33JVR"]
abcd$site = abcd$site.x


abcd = abcd[order(abcd$src_subject_id.x, abcd$interview_age.x, decreasing = FALSE), ]

abcd$GMV = with(abcd, smri_vol_scs_wholeb - (smri_vol_scs_cbwmatterlh + smri_vol_scs_cbwmatterrh) - smri_vol_scs_allventricles - smri_vol_scs_subcorticalgv)

abcd$sGMV = abcd$smri_vol_scs_subcorticalgv
# abcd$sGMV %>% summary
abcd$WMV = with(abcd, smri_vol_scs_cbwmatterlh + smri_vol_scs_cbwmatterrh)
# abcd$WMV %>% summary

abcd$age_years = abcd$interview_age.x / 12
abcd$sex_01 = ifelse(abcd$sex.x == "M", 1, 0)
abcd$GMV_10000 = abcd$GMV / 10000
abcd$sGMV_10000 = abcd$sGMV / 10000
abcd$WMV_10000 = abcd$WMV / 10000
# generate a new "numeric" id
# Note: geeglm has problem with ID values containing characters
abcd %<>% group_by(src_subject_id.x) %>% mutate(temp_id = cur_group_id()) 

# covert to `data.frame`
abcd %<>% as.data.frame
# colnames(abcd_smri_tbss)

abcd$eventname.x %<>% factor(levels = c("baseline_year_1_arm_1", "2_year_follow_up_y_arm_1"), labels = c("Baseline", "1-year follow-up"))

label(abcd$nihtbx_picvocab_fc) = "Picture Vocabulary Test"
label(abcd$nihtbx_flanker_fc) = "Flanker Inhibitory Control and Attention Test"
label(abcd$nihtbx_list_fc) = "List Sorting Working Memory Test"
label(abcd$nihtbx_cardsort_fc) = "Dimensional Change Card Sort Test"
label(abcd$nihtbx_pattern_fc) = "Pattern Comparison Processing Speed Test"
label(abcd$nihtbx_picture_fc) = "Picture Sequence Memory Test"
label(abcd$nihtbx_reading_fc) = "Oral Reading Recognition Test"
label(abcd$nihtbx_fluidcomp_fc) = "Cognition Fluid Composite"
label(abcd$nihtbx_cryst_fc) = "Crystallized Composite"
label(abcd$nihtbx_totalcomp_fc) = "Cognition Total Composite Score"

saveRDS(abcd, "data/analysis_data/abcd_psycho_data.rds")
```

```{r, eval = FALSE}
# Preparing the datasets for each psychometric variable analysis
abcd = readRDS("data/analysis_data/abcd_psycho_data.rds")

# the variables having enough 2nd-year follow-ups
var_long = c("nihtbx_picvocab_fc", # NIH Toolbox Picture Vocabulary Test Age 3+ v2.0
                          "nihtbx_flanker_fc", # NIH Toolbox Flanker Inhibitory Control and Attention Test Ages 8-11 v2.0
                          "nihtbx_pattern_fc",  # Pattern Comparison Processing Speed Test Age 7
                          "nihtbx_picture_fc", # Picture Sequence Memory Test Age 8+ Form A
                          "nihtbx_reading_fc", # Oral Reading Recognition Test Age 3+
                          "nihtbx_cryst_fc"# Crystallized Composite
                    )

# the variables NOT having enough 2nd-year follow-ups
var_cs = c("nihtbx_list_fc", # List Sorting Working Memory Test Age 7+ v2.0
           "nihtbx_cardsort_fc", # Dimensional Change Card Sort Test Ages 8-11 v2.0
           "nihtbx_fluidcomp_fc", # Cognition Fluid Composite
           "nihtbx_totalcomp_fc" # Cognition Total Composite Score
          )

var_list = c("temp_id", "age_years", "sex_01", "GMV_10000", "sGMV_10000", "WMV_10000", "eventname.x", "site")

# CS data: only keeping the baseline measurements
for (a in var_cs){
  print(a)
  temp_dat = abcd[, c(var_list, a)]
  temp_dat %<>% rename("psycho" = a)
  # calculate (1) the num of measurements per subject and (2) difference in psycho_var 
  temp_dat %<>% group_by(temp_id) %>% mutate(num_obs = length(eventname.x))
  # only remain the baseline measurements
  temp_dat = subset(temp_dat, eventname.x == "Baseline" )
  temp_dat = na.omit(temp_dat)
  temp_dat = temp_dat[order(temp_dat$temp_id, temp_dat$age_years), ]
  # ComBat
  combat_obj = neuroCombat::neuroCombat(dat = temp_dat[, c("GMV_10000", "sGMV_10000", "WMV_10000")] %>% t(), 
                                        mod = model.matrix(~ ns(age_years, df = 2) + sex_01 + psycho, data=temp_dat),
                                        batch = temp_dat$site, eb = TRUE, mean.only = TRUE, verbose = FALSE)
  
  temp_dat[, c("GMV_10000_combat", "sGMV_10000_combat", "WMV_10000_combat")] =  t(combat_obj$dat.combat)
  
  saveRDS(temp_dat, paste0("psycho_results/data_", a, ".rds"))
}

# longitudinal data: keep the subjects with both measurements
for (a in var_long){
  print(a)
  temp_dat = abcd[, c(var_list, a)]
  temp_dat %<>% rename("psycho" = a)
  # calculate (1) the num of measurements per subject and (2) difference in psycho_var 
  temp_dat %<>% group_by(temp_id) %>% mutate(num_obs = length(eventname.x),
                                             abs_diff_psycho = max(psycho) - min(psycho),
                                             diff_psycho = psycho[2] - psycho[1],
                                             diff_GMV = GMV_10000[2] - GMV_10000[1])
  # only remain the data from subject with both measurements
  temp_dat = subset(temp_dat, num_obs == 2 & !is.na(abs_diff_psycho))
  # longComBat
  temp_dat = na.omit(temp_dat)
  temp_dat = temp_dat[order(temp_dat$temp_id, temp_dat$age_years), ]
  temp_dat %<>% as.data.frame
  combat_obj = longCombat::longCombat(idvar = "temp_id", 
                                     timevar = "age_years", 
                                     batchvar = "site", 
                                     features = paste0(c("GMV", "sGMV", "WMV"), "_10000"),
                                     formula = "ns(age_years, df = 2) + sex_01 + psycho",
                                     ranef = "(1|temp_id)",
                                     data = temp_dat,
                                     verbose = FALSE)   
  temp_dat[, c("GMV_10000_combat", "sGMV_10000_combat", "WMV_10000_combat")] = combat_obj$data_combat[, c("GMV_10000.combat", "sGMV_10000.combat", "WMV_10000.combat")]
  
  saveRDS(temp_dat, paste0("data/analysis_data/ABCD_psycho_measure_combat/data_", a, ".rds"))
}
```


## Tab. S7
```{r}
abcd <- readRDS("data/analysis_data/abcd_psycho_data.rds")

my.render.cont <- function(x) {
    with(stats.default(x), 
         c("",
           
          "Mean (SD)" = sprintf("%s (%s)",
                                round_pad(MEAN, 1),
                                round_pad(SD, 1)),
         
          "Median (Min, Max)" = sprintf("%s (%s, %s)",
                                       round_pad(MEDIAN, 1), 
                                       round_pad(MIN, 1), 
                                       round_pad(MAX, 1)),
          "N" = sprintf("%s",
                        N))
    )
}


table1(~ nihtbx_picvocab_fc + nihtbx_flanker_fc + nihtbx_list_fc + nihtbx_list_fc + nihtbx_cardsort_fc + nihtbx_pattern_fc + nihtbx_picture_fc + nihtbx_reading_fc + nihtbx_fluidcomp_fc + nihtbx_cryst_fc + nihtbx_totalcomp_fc | eventname.x, data = abcd, reder = my.render.cont)
```

# The ES of each cognitive variable on GMV (Tab. 2)


```{r}
# the variables having enough 2nd-year follow-ups
var_long = c("nihtbx_picvocab_fc", # NIH Toolbox Picture Vocabulary Test Age 3+ v2.0
                          "nihtbx_flanker_fc", # NIH Toolbox Flanker Inhibitory Control and Attention Test Ages 8-11 v2.0
                          "nihtbx_pattern_fc",  # Pattern Comparison Processing Speed Test Age 7
                          "nihtbx_picture_fc", # Picture Sequence Memory Test Age 8+ Form A
                          "nihtbx_reading_fc", # Oral Reading Recognition Test Age 3+
                          "nihtbx_cryst_fc"# Crystallized Composite
                    )

# the variables NOT having enough 2nd-year follow-ups
var_cs = c("nihtbx_list_fc", # List Sorting Working Memory Test Age 7+ v2.0
           "nihtbx_cardsort_fc", # Dimensional Change Card Sort Test Ages 8-11 v2.0
           "nihtbx_fluidcomp_fc", # Cognition Fluid Composite
           "nihtbx_totalcomp_fc" # Cognition Total Composite Score
          )

var_long_lab = c("Picture Vocabulary",
                 "Flanker Inhibitory Control and Attention",
                 "Pattern Comparison Processing Speed",
                 "Picture Sequence Memory",
                 "Oral Reading Recognition",
                 "Crystallized Composite")

var_cs_lab = c("List Sorting Working Memory", 
               "Dimensional Change Card Sort",
               "Cognition Fluid Composite",
               "Cognition Total Composite Score")

list_cs = data.frame(psycho_var = var_cs, lab = var_cs_lab, design = "CS")
list_long = data.frame(psycho_var = var_long, lab = var_long_lab, design = "long")
list = rbind(list_cs, list_long)
```

```{r, eavl = FALSE}
set.seed(2023)
for (i in 1:nrow(list)){
  var_i = list$psycho_var[i]
  design_i = list$design[i]
  cat("Psychometric variable: ", var_i, "\n")
  
  data_i =  readRDS(paste0("~/RESI/longitudinal/data_analysis/data/analysis_data/ABCD_psycho_measure_combat/data_", var_i, ".rds"))
  
  formula_GMV = GMV_10000_combat ~ ns(age_years, df = 2) + sex_01 + psycho
  formula_sGMV = sGMV_10000_combat ~ ns(age_years, df = 2) + sex_01 + psycho
  formula_WMV = WMV_10000_combat ~ ns(age_years, df = 2) + sex_01 + psycho
  
  if (design_i == "CS"){
    # fit
    fit_GMV = lm(formula_GMV, data = data_i)
    fit_sGMV = lm(formula_sGMV, data = data_i)
    fit_WMV = lm(formula_WMV, data = data_i)

    # RESI objects
    resi_GMV = RESI::resi(fit_GMV, data = data_i)
    resi_sGMV = RESI::resi(fit_sGMV, data = data_i)
    resi_WMV = RESI::resi(fit_WMV, data = data_i)
    
    saveRDS(resi_GMV, paste0("~/RESI/longitudinal/data_analysis/RESI_objects/psycho_measure/GMV/RESI_psycho_", var_i, ".rds"))
    saveRDS(resi_sGMV, paste0("~/RESI/longitudinal/data_analysis/RESI_objects/psycho_measure/sGMV/RESI_psycho_", var_i, ".rds"))
    saveRDS(resi_WMV, paste0("~/RESI/longitudinal/data_analysis/RESI_objects/psycho_measure/WMV/RESI_psycho_", var_i, ".rds"))
  }
  
  if (design_i == "long"){
    # fit
    fit_GMV = geeglm(formula_GMV, id = temp_id, data = data_i, corstr = "exchangeable")
    fit_sGMV = geeglm(formula_sGMV, id = temp_id, data = data_i, corstr = "exchangeable")
    fit_WMV = geeglm(formula_WMV, id = temp_id, data = data_i, corstr = "exchangeable")

    # RESI objects
    resi_GMV = resi_geeglm(fit_GMV, data = data_i)$anova
    resi_sGMV = resi_geeglm(fit_sGMV, data = data_i)$anova
    resi_WMV = resi_geeglm(fit_WMV, data = data_i)$anova
    
    saveRDS(resi_GMV, paste0("~/RESI/longitudinal/data_analysis/RESI_objects/psycho_measure/GMV/RESI_psycho_", var_i, ".rds"))
    saveRDS(resi_sGMV, paste0("~/RESI/longitudinal/data_analysis/RESI_objects/psycho_measure/sGMV/RESI_psycho_", var_i, ".rds"))
    saveRDS(resi_WMV, paste0("~/RESI/longitudinal/data_analysis/RESI_objects/psycho_measure/WMV/RESI_psycho_", var_i, ".rds"))

  }
  
}
```


## Table 2 
```{r}
# the variables having enough 2nd-year follow-ups
var_long = c("nihtbx_picvocab_fc", # NIH Toolbox Picture Vocabulary Test Age 3+ v2.0
              "nihtbx_flanker_fc", # NIH Toolbox Flanker Inhibitory Control and Attention Test Ages 8-11 v2.0
              "nihtbx_pattern_fc",  # Pattern Comparison Processing Speed Test Age 7
              "nihtbx_picture_fc", # Picture Sequence Memory Test Age 8+ Form A
              "nihtbx_reading_fc", # Oral Reading Recognition Test Age 3+
              "nihtbx_cryst_fc"# Crystallized Composite
                    )

# the variables NOT having enough 2nd-year follow-ups
var_cs = c("nihtbx_list_fc", # List Sorting Working Memory Test Age 7+ v2.0
           "nihtbx_cardsort_fc", # Dimensional Change Card Sort Test Ages 8-11 v2.0
           "nihtbx_fluidcomp_fc", # Cognition Fluid Composite
           "nihtbx_totalcomp_fc" # Cognition Total Composite Score
          )

var_long_lab = c("Picture Vocabulary",
                 "Flanker Inhibitory Control and Attention",
                 "Pattern Comparison Processing Speed",
                 "Picture Sequence Memory",
                 "Oral Reading Recognition",
                 "Crystallized Composite")

var_cs_lab = c("List Sorting Working Memory", 
               "Dimensional Change Card Sort",
               "Cognition Fluid Composite",
               "Cognition Total Composite Score")

list_cs = data.frame(psycho_var = var_cs, lab = var_cs_lab, design = "CS")
list_long = data.frame(psycho_var = var_long, lab = var_long_lab, design = "long")
list = rbind(list_cs, list_long)

list$`CS-RESI` = NA
list$`L-RESI` = NA
list_GMV = list_sGMV = list_WMV = list
for (i in 1:nrow(list)){
  var_i = list$psycho_var[i]
  resi_obj_GMV = readRDS(paste0("RESI_objects/psycho_measure/GMV/RESI_psycho_", var_i, ".rds"))
  resi_obj_sGMV = readRDS(paste0("RESI_objects/psycho_measure/sGMV/RESI_psycho_", var_i, ".rds"))
  resi_obj_WMV = readRDS(paste0("RESI_objects/psycho_measure/WMV/RESI_psycho_", var_i, ".rds"))
  if (list$design[i] == "long"){
  obj_GMV = resi_obj_GMV %>% round(2)
  obj_sGMV = resi_obj_sGMV %>% round(2)
  obj_WMV = resi_obj_WMV %>% round(2)
  # CS-RESI
  list_GMV$`CS-RESI`[i] = paste0(obj_GMV["psycho", "CS-RESI"], " (", obj_GMV["psycho", "CS 2.5%"], ", ", obj_GMV["psycho", "CS 97.5%"], ")")
  list_sGMV$`CS-RESI`[i] = paste0(obj_sGMV["psycho", "CS-RESI"], " (", obj_sGMV["psycho", "CS 2.5%"], ", ", obj_sGMV["psycho", "CS 97.5%"], ")")
  list_WMV$`CS-RESI`[i] = paste0(obj_WMV["psycho", "CS-RESI"], " (", obj_WMV["psycho", "CS 2.5%"], ", ", obj_WMV["psycho", "CS 97.5%"], ")")
  # L-RESI
  list_GMV$`L-RESI`[i] = paste0(obj_GMV["psycho", "L-RESI"], " (", obj_GMV["psycho", "L 2.5%"], ", ", obj_GMV["psycho", "L 97.5%"], ")")
  list_sGMV$`L-RESI`[i] = paste0(obj_sGMV["psycho", "L-RESI"], " (", obj_sGMV["psycho", "L 2.5%"], ", ", obj_sGMV["psycho", "L 97.5%"], ")")
  list_WMV$`L-RESI`[i] = paste0(obj_WMV["psycho", "L-RESI"], " (", obj_WMV["psycho", "L 2.5%"], ", ", obj_WMV["psycho", "L 97.5%"], ")")
  }
  if (list$design[i] == "CS"){
  # RESI
  obj_GMV = resi_obj_GMV$anova %>% round(2)
  obj_sGMV = resi_obj_sGMV$anova %>% round(2)
  obj_WMV = resi_obj_WMV$anova %>% round(2)

  list_GMV$`CS-RESI`[i] = paste0(obj_GMV["psycho", "RESI"], " (", obj_GMV["psycho", "2.5%"], ", ", obj_GMV["psycho", "97.5%"], ")")
  list_sGMV$`CS-RESI`[i] = paste0(obj_sGMV["psycho", "RESI"], " (", obj_sGMV["psycho", "2.5%"], ", ", obj_sGMV["psycho", "97.5%"], ")")
  list_WMV$`CS-RESI`[i] = paste0(obj_WMV["psycho", "RESI"], " (", obj_WMV["psycho", "2.5%"], ", ", obj_WMV["psycho", "97.5%"], ")")
  }
}
list_GMV
```

# Resampling 

```{r, eval = FALSE}
psycho_resamp_func = function(dat, data_bl, N, CS_psycho, resamp_scheme_bl, resamp_scheme_diff){
  boot_values = rep(NA, 6)
  names(boot_values) = as.vector(outer(c("L_RESI_", "CS_RESI_"), c("GMV", "sGMV", "WMV"), paste0))
  
  # obtain the bootstrap data
  if (CS_psycho){
    if (resamp_scheme_bl == 0) boot_id = sample(data_bl$temp_id, size = N, replace = TRUE)
    if (resamp_scheme_bl == 1) boot_id = sample(data_bl$temp_id, size = N, replace = TRUE, prob = data_bl$resamp_bl_prob)
    boot_data = dat[unlist(lapply(boot_id, function(x) which(x == dat$temp_id))), ]
  }
  
  if (!CS_psycho){
    if (resamp_scheme_bl == 0 & resamp_scheme_diff == 0) boot_id = sample(data_bl$temp_id, size = N, replace = TRUE)
    if (resamp_scheme_bl == 0 & resamp_scheme_diff == 1) boot_id = sample(data_bl$temp_id, size = N, replace = TRUE, prob = data_bl$resamp_diff_prob)
    if (resamp_scheme_bl == 1 & resamp_scheme_diff == 0) boot_id = sample(data_bl$temp_id, size = N, replace = TRUE, prob = data_bl$resamp_bl_prob)
    if (resamp_scheme_bl == 1 & resamp_scheme_diff == 1) boot_id = sample(data_bl$temp_id, size = N, replace = TRUE, prob = data_bl$resamp_bl_prob * data_bl$resamp_diff_prob)
    boot_data = dat[unlist(lapply(boot_id, function(x) which(x == dat$temp_id))), ]
    # Assign new ID to the bootstrap data
    boot_data$new_id = rep(1:length(boot_id),
                             times = unlist(lapply(boot_id, function(x) length(which(x==dat$temp_id))))
                           )
  }
  
  boot_data = na.omit(boot_data)
  if (!CS_psycho) {boot_data = boot_data[order(boot_data$new_id, boot_data$age_years), ]}
  boot_data %<>% as.data.frame
  
  # obtain the ES of the psychometric variable
  # formulas 
  formula_GMV = GMV_10000_combat ~ ns(age_years, df = 2) + sex_01 + psycho
  formula_sGMV = sGMV_10000_combat ~ ns(age_years, df = 2) + sex_01 + psycho
  formula_WMV = WMV_10000_combat ~ ns(age_years, df = 2) + sex_01 + psycho

  if (CS_psycho){
    # lm model fits
    boot_fit_GMV = lm(formula_GMV, data = boot_data)
    boot_fit_sGMV = lm(formula_sGMV, data = boot_data)
    boot_fit_WMV = lm(formula_WMV, data = boot_data)
    # RESI objects
    boot_resi_GMV = RESI::resi_pe(boot_fit_GMV, data = boot_data)
    boot_resi_sGMV = RESI::resi_pe(boot_fit_sGMV, data = boot_data)
    boot_resi_WMV = RESI::resi_pe(boot_fit_WMV, data = boot_data)
    # return values
    boot_values["CS_RESI_GMV"] = boot_resi_GMV$anova["psycho", "RESI"]
    boot_values["CS_RESI_sGMV"] = boot_resi_sGMV$anova["psycho", "RESI"]
    boot_values["CS_RESI_WMV"] = boot_resi_WMV$anova["psycho", "RESI"]
    
  } else {
    # GEE model fits
    boot_fit_GMV = geeglm(formula_GMV, id = new_id, data = boot_data, corstr = "exchangeable")
    boot_fit_sGMV = geeglm(formula_sGMV, id = new_id, data = boot_data, corstr = "exchangeable")
    boot_fit_WMV = geeglm(formula_WMV, id = new_id, data = boot_data, corstr = "exchangeable")
    # RESI
    boot_resi_GMV = resi_pe_geeglm(boot_fit_GMV, data = boot_data)$anova
    boot_resi_sGMV = resi_pe_geeglm(boot_fit_sGMV, data = boot_data)$anova
    boot_resi_WMV = resi_pe_geeglm(boot_fit_WMV, data = boot_data)$anova
    # return values
    # GMV
    boot_values["CS_RESI_GMV"] = boot_resi_GMV["psycho", "CS-RESI"]
    boot_values["L_RESI_GMV"] = boot_resi_GMV["psycho", "L-RESI"]
    # sGMV
    boot_values["CS_RESI_sGMV"] = boot_resi_sGMV["psycho", "CS-RESI"]
    boot_values["L_RESI_sGMV"] = boot_resi_sGMV["psycho", "L-RESI"]
    # WMV
    boot_values["CS_RESI_WMV"] = boot_resi_WMV["psycho", "CS-RESI"]
    boot_values["L_RESI_WMV"] = boot_resi_WMV["psycho", "L-RESI"]

  }
  return(boot_values)
  
}
```


```{r, eval = FALSE}
Sys.time()
abcd <- readRDS("data/analysis_data/abcd_psycho_data.rds")

set.seed(2023)

# RESAMPLING

nsim = 1000
num.cores = 40
## CS psychometric variables
psycho_var = c(var_cs, var_long)

Ns = seq(50, 10000, by = 500)

# between-subject resampling scheme.
resamp_schemes = 0:1

for (a in psycho_var[8:10]) { # a = psycho_var[8]
  print(a)
  
  dat = readRDS(paste0("~/RESI/longitudinal/data_analysis/psycho_results/data_", a, ".rds"))
  
  CS_psycho = ifelse(sum(dat$eventname.x != "Baseline") > 0, FALSE, TRUE)
  
  if (CS_psycho) {
    output = expand.grid(N = Ns, resamp_scheme_bl = resamp_schemes)
  } else {
    output = expand.grid(N = Ns, resamp_scheme_bl = resamp_schemes, resamp_scheme_diff = resamp_schemes)
  }
  
  output = list(GMV = cbind(output, 
                             mean_CS_RESI = NA, CS_RESI_ll = NA, CS_RESI_ul = NA, 
                             mean_L_RESI = NA, L_RESI_ll = NA, L_RESI_ul = NA
                             ),
                sGMV = cbind(output, 
                             mean_CS_RESI = NA, CS_RESI_ll = NA, CS_RESI_ul = NA, 
                             mean_L_RESI = NA, L_RESI_ll = NA, L_RESI_ul = NA
                             ),
                WMV = cbind(output, 
                             mean_CS_RESI = NA, CS_RESI_ll = NA, CS_RESI_ul = NA, 
                             mean_L_RESI = NA, L_RESI_ll = NA, L_RESI_ul = NA
                             )
  )
  
  # 1. calculate the resampling probabilities
  ## derive the baseline dataset
  data_bl = subset(dat, eventname.x == "Baseline")
  ## calculate the percentile of psychometric measurement
  data_bl$psycho_bl_perc = rank(data_bl$psycho) / nrow(data_bl)
  data_bl$resamp_bl_prob = with(data_bl, 2 * (data_bl$psycho_bl_perc - 0.5)^2)
  
  if (!CS_psycho) {
    data_bl$psycho_diff_perc = rank(data_bl$abs_diff_psycho) / nrow(data_bl)
    data_bl$resamp_diff_prob = with(data_bl, data_bl$psycho_diff_perc)
  }

  # 2. resampling
  for (i in 1:nrow(output$GMV)){
    print(i)
    N = output$GMV$N[i]
    resamp_scheme_bl = output$GMV$resamp_scheme_bl[i]
    resamp_scheme_diff = output$GMV$resamp_scheme_diff[i]
    
    temp = simplify2array(
                  mclapply(1:nsim, function(simInd, dat, data_bl, N, CS_psycho, resamp_scheme_bl, resamp_scheme_diff ){
                    rep = psycho_resamp_func(dat = dat, data_bl = data_bl, N = N, 
                                             CS_psycho = CS_psycho, resamp_scheme_bl = resamp_scheme_bl, resamp_scheme_diff = resamp_scheme_diff)
    
                    return(rep)
                  },
                  dat = dat, 
                  data_bl = data_bl, N = N, 
                  CS_psycho = CS_psycho, 
                  resamp_scheme_bl = resamp_scheme_bl, 
                  resamp_scheme_diff = resamp_scheme_diff,
                  mc.cores = num.cores
                  )) %>% t()   
    
    # GMV
    if (CS_psycho) {
      ind = which(output$GMV$N == N & output$GMV$resamp_scheme_bl == resamp_scheme_bl)
    } else {
      ind = which(output$GMV$N == N & output$GMV$resamp_scheme_bl == resamp_scheme_bl & output$GMV$resamp_scheme_diff == resamp_scheme_diff)
      }
    ## mean
    col_mean = colMeans(temp, na.rm = TRUE)
    output$GMV[ind, "mean_CS_RESI"] = col_mean["CS_RESI_GMV"]
    output$GMV[ind, "mean_L_RESI"] = col_mean["L_RESI_GMV"]    
    # lower bound
    output$GMV[ind, "CS_RESI_ll"] = apply(temp, 2, quantile, probs = c(0.025), na.rm = TRUE)["CS_RESI_GMV"]
    output$GMV[ind, "L_RESI_ll"] = apply(temp, 2, quantile, probs = c(0.025), na.rm = TRUE)["L_RESI_GMV"]   
    ## upper bound
    output$GMV[ind, "CS_RESI_ul"] = apply(temp, 2, quantile, probs = c(0.975), na.rm = TRUE)["CS_RESI_GMV"]
    output$GMV[ind, "L_RESI_ul"] = apply(temp, 2, quantile, probs = c(0.975), na.rm = TRUE)["L_RESI_GMV"]   
    
    # sGMV
    if (CS_psycho) {
      ind = which(output$sGMV$N == N & output$sGMV$resamp_scheme_bl == resamp_scheme_bl)
    } else {
      ind = which(output$sGMV$N == N & output$sGMV$resamp_scheme_bl == resamp_scheme_bl & output$sGMV$resamp_scheme_diff == resamp_scheme_diff)
      }
    ## mean
    output$sGMV[ind, "mean_CS_RESI"] = colMeans(temp, na.rm = TRUE)["CS_RESI_sGMV"]
    output$sGMV[ind, "mean_L_RESI"] = colMeans(temp, na.rm = TRUE)["L_RESI_sGMV"]    
    # lower bound
    output$sGMV[ind, "CS_RESI_ll"] = apply(temp, 2, quantile, probs = c(0.025), na.rm = TRUE)["CS_RESI_sGMV"]
    output$sGMV[ind, "L_RESI_ll"] = apply(temp, 2, quantile, probs = c(0.025), na.rm = TRUE)["L_RESI_sGMV"]   
    ## upper bound
    output$sGMV[ind, "CS_RESI_ul"] = apply(temp, 2, quantile, probs = c(0.975), na.rm = TRUE)["CS_RESI_sGMV"]
    output$sGMV[ind, "L_RESI_ul"] = apply(temp, 2, quantile, probs = c(0.975), na.rm = TRUE)["L_RESI_sGMV"]   
    
    # WMV
    if (CS_psycho) {
      ind = which(output$WMV$N == N & output$WMV$resamp_scheme_bl == resamp_scheme_bl)
    } else {
      ind = which(output$WMV$N == N & output$WMV$resamp_scheme_bl == resamp_scheme_bl & output$WMV$resamp_scheme_diff == resamp_scheme_diff)
      }
    ## mean
    output$WMV[ind, "mean_CS_RESI"] = colMeans(temp, na.rm = TRUE)["CS_RESI_WMV"]
    output$WMV[ind, "mean_L_RESI"] = colMeans(temp, na.rm = TRUE)["L_RESI_WMV"]    
    # lower bound
    output$WMV[ind, "CS_RESI_ll"] = apply(temp, 2, quantile, probs = c(0.025), na.rm = TRUE)["CS_RESI_WMV"]
    output$WMV[ind, "L_RESI_ll"] = apply(temp, 2, quantile, probs = c(0.025), na.rm = TRUE)["L_RESI_WMV"]   
    ## upper bound
    output$WMV[ind, "CS_RESI_ul"] = apply(temp, 2, quantile, probs = c(0.975), na.rm = TRUE)["CS_RESI_WMV"]
    output$WMV[ind, "L_RESI_ul"] = apply(temp, 2, quantile, probs = c(0.975), na.rm = TRUE)["L_RESI_WMV"]   
    
  }

  # saveRDS(output, paste0("psycho_results/results/psycho_resamp_result_", a, ".rds"))
}
Sys.time()
```


### "CS" psychometric measurements

```{r}
# the variables having enough 2nd-year follow-ups
var_long = c("nihtbx_picvocab_fc", # NIH Toolbox Picture Vocabulary Test Age 3+ v2.0
                          "nihtbx_flanker_fc", # NIH Toolbox Flanker Inhibitory Control and Attention Test Ages 8-11 v2.0
                          "nihtbx_pattern_fc",  # Pattern Comparison Processing Speed Test Age 7
                          "nihtbx_picture_fc", # Picture Sequence Memory Test Age 8+ Form A
                          "nihtbx_reading_fc", # Oral Reading Recognition Test Age 3+
                          "nihtbx_cryst_fc"# Crystallized Composite
                    )
var_long_lab = c("Picture Vocabulary",
                 "Flanker Inhibitory Control and Attention",
                 "Pattern Comparison Processing Speed",
                 "Picture Sequence Memory",
                 "Oral Reading Recognition",
                 "Crystallized Composite")

# the variables NOT having enough 2nd-year follow-ups
var_cs = c("nihtbx_list_fc", # List Sorting Working Memory Test Age 7+ v2.0
           "nihtbx_cardsort_fc", # Dimensional Change Card Sort Test Ages 8-11 v2.0
           "nihtbx_fluidcomp_fc", # Cognition Fluid Composite
           "nihtbx_totalcomp_fc" # Cognition Total Composite Score
          )
var_cs_lab = c("List Sorting Working Memory", 
               "Dimensional Change Card Sort",
               "Cognition Fluid Composite",
               "Cognition Total Composite Score")

# label(abcd$nihtbx_picvocab_fc) = "Picture Vocabulary Test"
# label(abcd$nihtbx_flanker_fc) = "Flanker Inhibitory Control and Attention Test"
# label(abcd$nihtbx_list_fc) = "List Sorting Working Memory Test"
# label(abcd$nihtbx_cardsort_fc) = "Dimensional Change Card Sort Test"
# label(abcd$nihtbx_pattern_fc) = "Pattern Comparison Processing Speed Test"
# label(abcd$nihtbx_picture_fc) = "Picture Sequence Memory Test"
# label(abcd$nihtbx_reading_fc) = "Oral Reading Recognition Test"
# label(abcd$nihtbx_fluidcomp_fc) = "Cognition Fluid Composite"
# label(abcd$nihtbx_cryst_fc) = "Crystallized Composite"
# label(abcd$nihtbx_totalcomp_fc) = "Cognition Total Composite Score"
```



```{r}
# the "CS" psychometric variables
plot_data = NULL
for (i in 1:length(var_cs)){
  psycho_obj <- readRDS(paste0("resampling_schemes/psycho_measure_ABCD/results/psycho_resamp_result_", var_cs[i], ".rds"))
  psycho_obj$GMV$psycho_var = var_cs_lab[i]
  plot_data = rbind(plot_data, psycho_obj$GMV)
}

plot_data$`Baseline Resampling Scheme` = ifelse(plot_data$resamp_scheme_bl == 0, "Scheme 0", "Scheme 1")

ggplot(data = plot_data, aes(x = N, y = mean_CS_RESI, color = `Baseline Resampling Scheme`, group = `Baseline Resampling Scheme`)) +  
    geom_ribbon(aes(ymin = CS_RESI_ll, ymax = CS_RESI_ul, fill =  `Baseline Resampling Scheme`), alpha=0.2, linetype = 0) + 
    geom_line(linewidth = 1) + 
  # scale_color_viridis_d(aesthetics = c("colour", "fill"), begin = 0.1, end = 0.95, option = 'viridis') + 
  theme_bw() + 
  labs(title = "", y = 'RESI', x = 'Sample size') + facet_wrap(~psycho_var) + 
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5)) 
```



### "Long" psychometric measurements

```{r, fig.width=10, fig.height=8}
# the "long" psycohmetric variables
plot_data = NULL
for (i in 1:length(var_long)){
  psycho_obj <- readRDS(paste0("resampling_schemes/psycho_measure_ABCD/results/psycho_resamp_result_", var_long[i], ".rds"))
  psycho_obj$GMV$psycho_var = var_long_lab[i]
  plot_data = rbind(plot_data, psycho_obj$GMV)
}

plot_data$`Baseline Resampling Scheme` = ifelse(plot_data$resamp_scheme_bl == 0, "Scheme 0", "Scheme 1")
plot_data$`Resampling Scheme based on Psychometric Assessment Change` =  ifelse(plot_data$resamp_scheme_diff == 0, "Scheme 0", "Scheme 1")
```


```{r, fig.width=6, fig.height=16}
# CS RESI
ggplot(data = plot_data, aes(x = N, y = mean_CS_RESI, color = `Baseline Resampling Scheme`, group = `Baseline Resampling Scheme`)) +  
    geom_ribbon(aes(ymin = CS_RESI_ll, ymax = CS_RESI_ul, fill =  `Baseline Resampling Scheme`), alpha=0.2, linetype = 0) + 
    geom_line(size = 1) + 
  # scale_color_viridis_d(aesthetics = c("colour", "fill"), begin = 0.1, end = 0.95, option = 'viridis') + 
  labs(title = "", y = 'CS-RESI', x = 'Sample size') + facet_grid(psycho_var ~ `Resampling Scheme based on Psychometric Assessment Change` ) + 
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5)) + theme_bw() + theme(legend.position = "bottom")
```


```{r, fig.width=6, fig.height=16}
# L-RESI
ggplot(data = plot_data, aes(x = N, y = mean_L_RESI, color = `Baseline Resampling Scheme`, group = `Baseline Resampling Scheme`)) +  
    geom_ribbon(aes(ymin = L_RESI_ll, ymax = L_RESI_ul, fill =  `Baseline Resampling Scheme`), alpha=0.2, linetype = 0) + 
    geom_line(size = 1) + 
  # scale_color_viridis_d(aesthetics = c("colour", "fill"), begin = 0.1, end = 0.95, option = 'viridis') + 
  # theme_classic() + 
  labs(title = "", y = 'L-RESI', x = 'Sample size') + facet_grid(psycho_var ~ `Resampling Scheme based on Psychometric Assessment Change` ) + 
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5)) + theme_bw() + theme(legend.position = "bottom")
```


