---
title: "Figure S4 - Forest plots of the sex effects"
author: "Kaidi Kang"
date: "2023-05-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, warning = FALSE, message = FALSE}
setwd("~/RESI/longitudinal/data_analysis")
analysis_data <- read_csv("data/analysis_data/analysis_data_combat.csv")
analysis_data %<>% as.data.frame # `tibble` will cause a lot of problems with current RESI package
study_info_clean <- read_csv("data/analysis_data/study_info_clean.csv")
study_info_clean %<>% as.data.frame

source("Code/functions/forest_plot.R")
```

## Fig S4. Forest plots of the sex effects

```{r, fig.height=10, fig.width=12}
# P1: forest plot of sex effect on GMV

RESI_GMV <- forest_plot(study_info = study_info_clean, outcome = "GMV", x_ul = 1.5)
p1 = RESI_GMV$plot_sex + labs(title = "Effects of Sex on GMV") 

RESI_sGMV <- forest_plot(study_info = study_info_clean, outcome = "sGMV", x_ul = 1.5)
p2 = RESI_sGMV$plot_sex + labs(title = "Effects of Sex on sGMV") 

RESI_WMV <- forest_plot(study_info = study_info_clean, outcome = "WMV", x_ul = 1.5)
p3 = RESI_WMV$plot_sex + labs(title = "Effects of Sex on WMV") 

P1 = plot_grid(p1, p2, p3, labels = c("(A)", "(B)", "(C)"), ncol = 3) %>% suppressWarnings()
P1
```