---
title: "Figure S9 -"
author: "Kaidi Kang"
date: "2023-05-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning = FALSE, message = FALSE}
setwd("~/RESI/longitudinal/data_analysis")
analysis_data <- read_csv("data/analysis_data/analysis_data_combat.csv")
analysis_data %<>% as.data.frame # `tibble` will cause a lot of problems with current RESI package
```



## Fig S9. Correlation in ADNI
```{r}
ADNI = subset(analysis_data, study == "ADNI")
ADNI = ADNI[order(ADNI$participant, ADNI$age_years), ]
ADNI_head = ADNI %>% group_by(participant) %>% slice_min(age_years)
ADNI_tail = ADNI %>% group_by(participant) %>% slice_max(age_years)
ADNI_head_tail = rbind(ADNI_head, ADNI_tail)
ADNI_head_tail = ADNI_head_tail[order(ADNI_head_tail$participant, ADNI_head_tail$age_years), ]
ADNI_bl = ADNI_head_tail %>% group_by(participant) %>% mutate(diff_GMV = GMV_10000_combat[2] - GMV_10000_combat[1], 
                                                     diff_age = age_years[2] - age_years[1]) %>% slice_head(n = 1)
```

```{r, fig.width = 3, fig.height=3}
ggplot(ADNI_bl, aes(x = diff_age, y = diff_GMV)) + geom_point() + geom_smooth(method = "lm", formula = "y ~ x") + labs(title = "ADNI", x = "Change in Age", y = "Change in GMV / 10000") + theme_bw()
```