---
title: "Figure 3 - Resampling schemes in UKB and ADNI"
author: "Kaidi Kang"
date: "2023-05-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Figure 3: Resampling schemes

```{r, fig.height=3, fig.width=12}
output <- readRDS("resampling_schemes/ADNI_UKB/resamp_scheme_UKB.rds")
output$scheme %<>% as.factor
# increase ES
p1 = ggplot(data = output, aes(x = N, y = mean_RESI_age, color = scheme, group = scheme)) +  
    geom_ribbon(aes(ymin = RESI_age_ll, ymax = RESI_age_ul, fill = scheme), alpha=0.2, linetype = 0) + 
    geom_line(size = 1) + # scale_color_viridis_d(aesthetics = c("colour", "fill"), begin = 0.1, end = 0.95, option = 'viridis') + 
  theme_classic() + labs(title = "", y = 'RESI for age', x = 'Sample size') + theme(legend.position = "none") + theme(axis.text.x = element_text(angle = 45, vjust = 0.5)) 

# sampling probabilities
scheme0 = data.frame(perc = seq(0, 1, by = 0.01), scheme = "Scheme 0", prob = 1) 
scheme1 = data.frame(perc = seq(0, 1, by = 0.01), scheme = "Scheme 1")
scheme1$prob = 2*abs(scheme1$perc - 0.5) 
scheme2 = data.frame(perc = seq(0, 1, by = 0.01), scheme = "Scheme 2")
scheme2$prob = 2*(scheme2$perc - 0.5)^2 / 0.5
data_plot = rbind(scheme0, scheme1, scheme2)

p2 = ggplot(data = data_plot, aes(x = perc, y = prob, color = scheme, group = scheme)) +  
    geom_line(size = 1) + # scale_color_viridis_d(aesthetics = c("colour"), begin = 0.1, end = 0.95, option = 'viridis') + 
  theme_classic() + labs(title = "", y = 'Relative probability', x = 'Age percentile') 

legend = get_legend(p2)

p2 = ggplot(data = data_plot, aes(x = perc, y = prob, color = scheme, group = scheme)) +  
    geom_line(size = 1) + # scale_color_viridis_d(aesthetics = c("colour"), begin = 0.1, end = 0.95, option = 'viridis') + 
  theme_classic() + labs(title = "Study: UKB", y = 'Relative probability', x = 'Age percentile') + theme(legend.position = "none")     


# resampled sd of age
p3 = ggplot(data = output, aes(x = N, y = mean_sd_age, color = scheme, group = scheme)) +  
    geom_ribbon(aes(ymin = sd_age_ll, ymax = sd_age_ul, fill = scheme), alpha=0.2, linetype = 0) + 
    geom_line(size = 1) + # scale_color_viridis_d(aesthetics = c("colour", "fill"), begin = 0.1, end = 0.95, option = 'viridis') + 
  theme_classic() + labs(title = "", y = 'SD of age', x = 'Sample size') + theme(legend.position = "none") + theme(axis.text.x = element_text(angle = 45, vjust = 0.5))     


P_UKB = plot_grid(NULL, p2, p3, p1, NULL,  labels = c("", "(A)", "(B)", "(C)", ""), rel_widths = c(0.25, 1, 1, 1, 0.25), nrow = 1) # %>% suppressWarnings()

```

```{r, fig.height = 10, fig.width=8}
# Resampling in ADNI
output <- readRDS("resampling_schemes/ADNI_UKB/resamp_scheme_ADNI_21Apr2023.rds")
output = subset(output, within_scheme != 999)
# reset upper limit
output$long_RESI_age_ul = ifelse(output$long_RESI_age_ul > 1.2, 1.2, output$long_RESI_age_ul)
output$CS_RESI_age_ul = ifelse(output$CS_RESI_age_ul > 1.2, 1.2, output$CS_RESI_age_ul)

output$`Within-subject Resampling Scheme` = factor(output$within_scheme, labels = c("Scheme 0", "Scheme 1", "Scheme 2"))
output$`Baseline Resampling Scheme` = factor(output$btwn_scheme, labels = c("Scheme 0", "Scheme 1", "Scheme 2"))


p1 = ggplot(data = output, aes(x = N, y = mean_CS_RESI_age, color = `Baseline Resampling Scheme`, group = `Baseline Resampling Scheme`)) + 
  geom_ribbon(aes(ymin = CS_RESI_age_ll, ymax = CS_RESI_age_ul, fill = `Baseline Resampling Scheme`), alpha=0.2, linetype = 0) +
  geom_line(size = 1) + 
  facet_wrap(~ `Within-subject Resampling Scheme`) + theme_bw() + theme(legend.position = "none") + theme(axis.text.x = element_text(angle = 45, vjust = 0.5))+ ylim(0, 1.25) + 
  labs(title = "Study: ADNI", y = 'CS-RESI', x = 'Sample size') 

  
p2 = ggplot(data = output, aes(x = N, y = mean_long_RESI_age, color = `Baseline Resampling Scheme`, group = `Baseline Resampling Scheme`)) + 
  geom_ribbon(aes(ymin = long_RESI_age_ll, ymax = long_RESI_age_ul, fill = `Baseline Resampling Scheme`), alpha=0.2, linetype = 0) +
  geom_line(size = 1) + facet_wrap(~ `Within-subject Resampling Scheme`) + labs(fill= "Baseline Resampling Scheme") + theme_bw() + theme(legend.position = "bottom") + 
  labs(title = "", y = 'L-RESI', x = 'Sample size') + ylim(0, 1.25)
legend = get_legend(p2)
p2 = ggplot(data = output, aes(x = N, y = mean_long_RESI_age, color = `Baseline Resampling Scheme`, group = `Baseline Resampling Scheme`)) + 
  geom_ribbon(aes(ymin = long_RESI_age_ll, ymax = long_RESI_age_ul, fill = `Baseline Resampling Scheme`), alpha=0.2, linetype = 0) +
  geom_line(size = 1) + facet_wrap(~ `Within-subject Resampling Scheme`) + labs(fill= "Baseline Resampling Scheme") + theme_bw() +   
  theme(legend.position = "none") + theme(axis.text.x = element_text(angle = 45, vjust = 0.5)) + 
  labs(title = "", y = 'L-RESI', x = 'Sample size') + ylim(0, 1.25)


P2 = plot_grid(p1, p2, 
               labels = "(D)",
               ncol = 1, rel_heights = c(1, 1)) %>% suppressWarnings()

# ggarrange(P1, P2, ncol = 1, heights = c(0.7, 2))

```


```{r, fig.height = 9, fig.width=10}
# two-obs resampling in ADNI

output$long_RESI_age_2obs_ul = ifelse(output$long_RESI_age_2obs_ul > 1.2, 1.2, output$long_RESI_age_2obs_ul)
output$CS_RESI_age_2obs_ul = ifelse(output$CS_RESI_age_2obs_ul > 1.2, 1.2, output$CS_RESI_age_2obs_ul)

p1 = ggplot(data = output, aes(x = N, y = mean_CS_RESI_age, color = `Baseline Resampling Scheme`, group = `Baseline Resampling Scheme`)) + 
  geom_ribbon(aes(ymin = CS_RESI_age_2obs_ll, ymax = CS_RESI_age_2obs_ul, fill = `Baseline Resampling Scheme`), alpha=0.2, linetype = 0) +
  geom_line(size = 1) + 
  facet_wrap(~ `Within-subject Resampling Scheme`) + theme_bw() + theme(legend.position = "none") + theme(axis.text.x = element_text(angle = 45, vjust = 0.5)) + ylim(0, 1.25) + 
  labs(title = "Study: ADNI (2-observation)", y = 'CS-RESI', x = 'Sample size') 


p2 = ggplot(data = output, aes(x = N, y = mean_long_RESI_age_2obs, color = `Baseline Resampling Scheme`, group = `Baseline Resampling Scheme`)) + 
  geom_ribbon(aes(ymin = long_RESI_age_2obs_ll, ymax = long_RESI_age_2obs_ul, fill = `Baseline Resampling Scheme`), alpha=0.2, linetype = 0) +
  geom_line(size = 1) + facet_wrap(~ `Within-subject Resampling Scheme`) + labs(fill= "Baseline Resampling Scheme") + theme_bw() +   
  theme(legend.position = "none") + theme(axis.text.x = element_text(angle = 45, vjust = 0.5)) + 
  labs(title = "", y = 'L-RESI', x = 'Sample size') + ylim(0, 1.25)

P3 = plot_grid(p1, p2,  labels = c("(E)"), rel_heights = c(1, 1), ncol = 1)


P_ADNI = plot_grid(P2, P3, rel_widths = c(1, 1), nrow = 1)
```


```{r, fig.height = 9, fig.width=10}
ggarrange(P_UKB, legend, P_ADNI, ncol = 1, heights = c(1, 0.2, 2))
```

