---
title: "Figure 4 -"
author: "Kaidi Kang"
date: "2023-05-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Figure 4. Resampling & the effect on ES in ABCD

```{r}
# the variables having enough 2nd-year follow-ups
var_long = c("nihtbx_picvocab_fc", # NIH Toolbox Picture Vocabulary Test Age 3+ v2.0
                          "nihtbx_flanker_fc", # NIH Toolbox Flanker Inhibitory Control and Attention Test Ages 8-11 v2.0
                          "nihtbx_pattern_fc",  # Pattern Comparison Processing Speed Test Age 7
                          "nihtbx_picture_fc", # Picture Sequence Memory Test Age 8+ Form A
                          "nihtbx_reading_fc", # Oral Reading Recognition Test Age 3+
                          "nihtbx_cryst_fc"# Crystallized Composite
                    )
var_long_lab = c("Picture Vocabulary",
                 "Flanker Inhibitory Control and Attention",
                 "Pattern Comparison Processing Speed",
                 "Picture Sequence Memory",
                 "Oral Reading Recognition",
                 "Crystallized Composite")

# the variables NOT having enough 2nd-year follow-ups
var_cs = c("nihtbx_list_fc", # List Sorting Working Memory Test Age 7+ v2.0
           "nihtbx_cardsort_fc", # Dimensional Change Card Sort Test Ages 8-11 v2.0
           "nihtbx_fluidcomp_fc", # Cognition Fluid Composite
           "nihtbx_totalcomp_fc" # Cognition Total Composite Score
          )
var_cs_lab = c("List Sorting Working Memory", 
               "Dimensional Change Card Sort",
               "Cognition Fluid Composite",
               "Cognition Total Composite Score")

```


```{r, fig.height=5, fig.width=4}
# resampling probability
data = data.frame(x = c(0, 1, 0, 1), y = c(0, 1, 0.5, 0.5))
data$"Within-subject Resampling Scheme" = c("Scheme 1", "Scheme 1", "Scheme 0", "Scheme 0")

p_prob = ggplot(data, aes(x = x, y = y, group = `Within-subject Resampling Scheme`, linetype = `Within-subject Resampling Scheme`)) + 
          geom_line(linewidth = 1) + 
          labs(title = "Within-subject resampling scheme", x = "Percentile in Absolute Change", y = "Relative probability") + 
          theme_bw()
legend_prob = get_legend(p_prob)

p_prob = ggplot(data, aes(x = x, y = y, group = `Within-subject Resampling Scheme`, linetype = `Within-subject Resampling Scheme`)) + 
          geom_line(linewidth = 1) + 
          labs(title = "Within-subject resampling scheme", x = "Percentile in Absolute Change", y = "Relative probability") + 
          theme_bw() + theme(legend.position = "none")

P0 = plot_grid(p_prob, legend_prob, labels = c("(A)", ""), rel_heights = c(1, 0.3), ncol = 1)

```


```{r, fig.width=4, fig.height=12}
# the "CS" psychometric variables
plot_data = NULL
for (i in 1:length(var_cs)){
  psycho_obj <- readRDS(paste0("~/RESI/longitudinal/data_analysis/resampling_schemes/psycho_measure_ABCD/results/psycho_resamp_result_", var_cs[i], ".rds"))
  psycho_obj$GMV$psycho_var = var_cs_lab[i]
  plot_data = rbind(plot_data, psycho_obj$GMV)
}

plot_data$`Baseline Resampling Scheme` = ifelse(plot_data$resamp_scheme_bl == 0, "Scheme 0", "Scheme 2")

p1 = ggplot(data = plot_data, aes(x = N, y = mean_CS_RESI, color = `Baseline Resampling Scheme`, group = `Baseline Resampling Scheme`)) +  
    geom_ribbon(aes(ymin = CS_RESI_ll, ymax = CS_RESI_ul, fill =  `Baseline Resampling Scheme`), alpha=0.2, linetype = 0) + 
    geom_line(linewidth = 1) + 
  # scale_color_viridis_d(aesthetics = c("colour", "fill"), begin = 0.1, end = 0.95, option = 'viridis') + 
  theme_bw() + 
  labs(title = "", y = 'RESI', x = 'Sample size') + facet_grid(rows = vars(psycho_var)) + 
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5)) + theme(legend.position = "none")
P1 = plot_grid(p1, labels = c("(B)"))
```


```{r, fig.width=10, fig.height=8}
# the "long" psycohmetric variables
plot_data = NULL
for (i in 1:length(var_long)){
  psycho_obj <- readRDS(paste0("~/RESI/longitudinal/data_analysis/resampling_schemes/psycho_measure_ABCD/results/psycho_resamp_result_", var_long[i], ".rds"))
  psycho_obj$GMV$psycho_var = var_long_lab[i]
  plot_data = rbind(plot_data, psycho_obj$GMV)
}

plot_data$`Baseline Resampling Scheme` = ifelse(plot_data$resamp_scheme_bl == 0, "Scheme 0", "Scheme 2")
plot_data$`Resampling Scheme based on Psychometric Assessment Change` =  ifelse(plot_data$resamp_scheme_diff == 0, "Within-subject Scheme 0", "Within-subject Scheme 1") %>% factor(levels = c("Within-subject Scheme 0", "Within-subject Scheme 1"))
```


```{r, fig.width=6, fig.height=16}
# CS RESI
p_cs = ggplot(data = plot_data, aes(x = N, y = mean_CS_RESI, color = `Baseline Resampling Scheme`, group = `Baseline Resampling Scheme`)) +  
        geom_ribbon(aes(ymin = CS_RESI_ll, ymax = CS_RESI_ul, fill =  `Baseline Resampling Scheme`), alpha=0.2, linetype = 0) + 
        geom_line(size = 1) + 
        # scale_color_viridis_d(aesthetics = c("colour", "fill"), begin = 0.1, end = 0.95, option = 'viridis') + 
        labs(title = "", y = 'CS-RESI', x = 'Sample size') + facet_grid(psycho_var ~ `Resampling Scheme based on Psychometric Assessment Change` ) + 
        theme_bw() + theme(legend.position = "none") + theme(axis.text.x = element_text(angle = 45, vjust = 0.5)) + ylim(0, 0.6) 


# L-RESI
p_long = ggplot(data = plot_data, aes(x = N, y = mean_L_RESI, color = `Baseline Resampling Scheme`, group = `Baseline Resampling Scheme`)) +  
          geom_ribbon(aes(ymin = L_RESI_ll, ymax = L_RESI_ul, fill =  `Baseline Resampling Scheme`), alpha=0.2, linetype = 0) + 
          geom_line(size = 1) + 
          # scale_color_viridis_d(aesthetics = c("colour", "fill"), begin = 0.1, end = 0.95, option = 'viridis') + 
          # theme_classic() + 
          labs(title = "", y = 'L-RESI', x = 'Sample size') + facet_grid(psycho_var ~ `Resampling Scheme based on Psychometric Assessment Change` ) + 
          theme(axis.text.x = element_text(angle = 45, vjust = 0.5)) + theme_bw() # + theme(legend.position = "bottom")

legend = get_legend(p_long)

p_long = ggplot(data = plot_data, aes(x = N, y = mean_L_RESI, color = `Baseline Resampling Scheme`, group = `Baseline Resampling Scheme`)) +  
          geom_ribbon(aes(ymin = L_RESI_ll, ymax = L_RESI_ul, fill =  `Baseline Resampling Scheme`), alpha=0.2, linetype = 0) + 
          geom_line(size = 1) + 
          # scale_color_viridis_d(aesthetics = c("colour", "fill"), begin = 0.1, end = 0.95, option = 'viridis') + 
          # theme_classic() + 
          labs(title = "", y = 'L-RESI', x = 'Sample size') + facet_grid(psycho_var ~ `Resampling Scheme based on Psychometric Assessment Change` ) + ylim(0, 0.6) + 
          theme_bw() + theme(legend.position = "none") + theme(axis.text.x = element_text(angle = 45, vjust = 0.5))

P2 = plot_grid(p_cs, p_long, labels = c("(C)"))
```

```{r, fig.width = 15, fig.height= 16}
grid.arrange(
  P0, P1, P2, legend,
  layout_matrix = rbind(c(1, 3),
                        c(2, 3),
                        c(4, 3)),
  widths = c(1.2, 4), heights = c(1.2, 3, 0.2)
) #%>% suppressWarnings()
```


