---
title: "Figure S5 - Between and within-subject SD of age in ADNI after resampling."
author: "Kaidi Kang"
date: "2023-05-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Fig S5. Between and within-subject SD of age in ADNI after resampling.
```{r, fig.height = 6, fig.width = 10}
output <- readRDS("resampling_schemes/ADNI_UKB/resamp_scheme_ADNI_21Apr2023.rds")

output$`Within-subject Resampling Scheme` = factor(output$within_scheme, labels = c("Scheme 0", "Scheme 1", "Scheme 2"))
output$`Baseline Resampling Scheme` = factor(output$btwn_scheme, labels = c("Scheme 0", "Scheme 1", "Scheme 2"))

# change of between-subject sd of age
p1 = ggplot(data = output, aes(x = N, y = mean_btwn_sd_age, color = `Baseline Resampling Scheme`, group = `Baseline Resampling Scheme`)) + 
  geom_ribbon(aes(ymin = btwn_sd_age_ll, ymax = btwn_sd_age_ul, fill = `Baseline Resampling Scheme`), alpha=0.2, linetype = 0) +
  geom_line(size = 1) + 
  facet_wrap(~ `Within-subject Resampling Scheme`) + theme_bw() + theme(legend.position = "none")  + 
  labs(title = " Study: ADNI", y = 'Between-subject SD of age', x = 'Sample size')


# change of within-subject sd of age
p2 = ggplot(data = output, aes(x = N, y = mean_within_sd_age, color = `Baseline Resampling Scheme`, group = `Baseline Resampling Scheme`)) + 
  geom_ribbon(aes(ymin = within_sd_age_ll, ymax = within_sd_age_ul, fill = `Baseline Resampling Scheme`), alpha=0.2, linetype = 0) +
  geom_line(size = 1) + 
  facet_wrap(~ `Within-subject Resampling Scheme`) + theme(legend.position = "bottom")  + 
  labs(title = "Study: ADNI", y = 'Within-subject SD of age', x = 'Sample size')
legend = get_legend(p2)
p2 = ggplot(data = output, aes(x = N, y = mean_within_sd_age, color = `Baseline Resampling Scheme`, group = `Baseline Resampling Scheme`)) + 
  geom_ribbon(aes(ymin = within_sd_age_ll, ymax = within_sd_age_ul, fill = `Baseline Resampling Scheme`), alpha=0.2, linetype = 0) +
  geom_line(size = 1) + 
  facet_wrap(~ `Within-subject Resampling Scheme`) + theme_bw() + theme(legend.position = "none")  + ylim(1, 5) +
  labs(title = " ", y = 'Within-subject SD of age', x = 'Sample size')

P1 = plot_grid(p1, p2, labels = c("(A)", ""), rel_heights = c(1, 1), ncol = 1)

# two-obs
p1 = ggplot(data = output, aes(x = N, y = mean_btwn_sd_age_2obs, color = `Baseline Resampling Scheme`, group = `Baseline Resampling Scheme`)) + 
  geom_ribbon(aes(ymin = btwn_sd_age_2obs_ll, ymax = btwn_sd_age_2obs_ul, fill = `Baseline Resampling Scheme`), alpha=0.2, linetype = 0) +
  geom_line(size = 1) + 
  facet_wrap(~ `Within-subject Resampling Scheme`) + theme_bw() + theme(legend.position = "none")  + 
  labs(title = " Study: ADNI (2-observation)", y = 'Between-subject SD of age', x = 'Sample size')


# change of within-subject sd of age
p2 = ggplot(data = output, aes(x = N, y = mean_within_sd_age_2obs, color = `Baseline Resampling Scheme`, group = `Baseline Resampling Scheme`)) + 
  geom_ribbon(aes(ymin = within_sd_age_2obs_ll, ymax = within_sd_age_2obs_ul, fill = `Baseline Resampling Scheme`), alpha=0.2, linetype = 0) +
  geom_line(size = 1) + 
  facet_wrap(~ `Within-subject Resampling Scheme`) + theme(legend.position = "bottom")  + 
  labs(title = "", y = 'Within-subject SD of age', x = 'Sample size')
legend = get_legend(p2)
p2 = ggplot(data = output, aes(x = N, y = mean_within_sd_age_2obs, color = `Baseline Resampling Scheme`, group = `Baseline Resampling Scheme`)) + 
  geom_ribbon(aes(ymin = within_sd_age_2obs_ll, ymax = within_sd_age_2obs_ul, fill = `Baseline Resampling Scheme`), alpha=0.2, linetype = 0) +
  geom_line(size = 1) + 
  facet_wrap(~ `Within-subject Resampling Scheme`) + theme_bw() + theme(legend.position = "none")  + ylim(1, 5) +
  labs(title = " ", y = 'Within-subject SD of age', x = 'Sample size')

P2 = plot_grid(p1, p2, labels = c("(B)", ""), rel_heights = c(1, 1), ncol = 1)

P3 = plot_grid(P1, P2, nrow = 1)

P4 = plot_grid(P3, legend, ncol = 1, rel_heights = c(1, 0.1))
P4
```