---
title: "Table 2 - ES estimates of each psycho measurement in ABCD"
author: "Kaidi Kang"
date: "2023-05-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Table 2 (ES estimates of each psycho measurement in ABCD)
```{r}
# the variables having enough 2nd-year follow-ups
var_long = c("nihtbx_picvocab_fc", # NIH Toolbox Picture Vocabulary Test Age 3+ v2.0
                          "nihtbx_flanker_fc", # NIH Toolbox Flanker Inhibitory Control and Attention Test Ages 8-11 v2.0
                          "nihtbx_pattern_fc",  # Pattern Comparison Processing Speed Test Age 7
                          "nihtbx_picture_fc", # Picture Sequence Memory Test Age 8+ Form A
                          "nihtbx_reading_fc", # Oral Reading Recognition Test Age 3+
                          "nihtbx_cryst_fc"# Crystallized Composite
                    )

# the variables NOT having enough 2nd-year follow-ups
var_cs = c("nihtbx_list_fc", # List Sorting Working Memory Test Age 7+ v2.0
           "nihtbx_cardsort_fc", # Dimensional Change Card Sort Test Ages 8-11 v2.0
           "nihtbx_fluidcomp_fc", # Cognition Fluid Composite
           "nihtbx_totalcomp_fc" # Cognition Total Composite Score
          )

var_long_lab = c("Picture Vocabulary",
                 "Flanker Inhibitory Control and Attention",
                 "Pattern Comparison Processing Speed",
                 "Picture Sequence Memory",
                 "Oral Reading Recognition",
                 "Crystallized Composite")

var_cs_lab = c("List Sorting Working Memory", 
               "Dimensional Change Card Sort",
               "Cognition Fluid Composite",
               "Cognition Total Composite Score")

list_cs = data.frame(psycho_var = var_cs, lab = var_cs_lab, design = "CS")
list_long = data.frame(psycho_var = var_long, lab = var_long_lab, design = "long")
list = rbind(list_cs, list_long)

list$`CS-RESI` = NA
list$`L-RESI` = NA
list_GMV = list_sGMV = list_WMV = list
for (i in 1:nrow(list)){
  var_i = list$psycho_var[i]
  resi_obj_GMV = readRDS(paste0("RESI_objects/psycho_measure/GMV/RESI_psycho_", var_i, ".rds"))
  resi_obj_sGMV = readRDS(paste0("RESI_objects/psycho_measure/sGMV/RESI_psycho_", var_i, ".rds"))
  resi_obj_WMV = readRDS(paste0("RESI_objects/psycho_measure/WMV/RESI_psycho_", var_i, ".rds"))
  if (list$design[i] == "long"){
  obj_GMV = resi_obj_GMV %>% round(2)
  obj_sGMV = resi_obj_sGMV %>% round(2)
  obj_WMV = resi_obj_WMV %>% round(2)
  # CS-RESI
  list_GMV$`CS-RESI`[i] = paste0(obj_GMV["psycho", "CS-RESI"], " (", obj_GMV["psycho", "CS 2.5%"], ", ", obj_GMV["psycho", "CS 97.5%"], ")")
  list_sGMV$`CS-RESI`[i] = paste0(obj_sGMV["psycho", "CS-RESI"], " (", obj_sGMV["psycho", "CS 2.5%"], ", ", obj_sGMV["psycho", "CS 97.5%"], ")")
  list_WMV$`CS-RESI`[i] = paste0(obj_WMV["psycho", "CS-RESI"], " (", obj_WMV["psycho", "CS 2.5%"], ", ", obj_WMV["psycho", "CS 97.5%"], ")")
  # L-RESI
  list_GMV$`L-RESI`[i] = paste0(obj_GMV["psycho", "L-RESI"], " (", obj_GMV["psycho", "L 2.5%"], ", ", obj_GMV["psycho", "L 97.5%"], ")")
  list_sGMV$`L-RESI`[i] = paste0(obj_sGMV["psycho", "L-RESI"], " (", obj_sGMV["psycho", "L 2.5%"], ", ", obj_sGMV["psycho", "L 97.5%"], ")")
  list_WMV$`L-RESI`[i] = paste0(obj_WMV["psycho", "L-RESI"], " (", obj_WMV["psycho", "L 2.5%"], ", ", obj_WMV["psycho", "L 97.5%"], ")")
  }
  if (list$design[i] == "CS"){
  # RESI
  obj_GMV = resi_obj_GMV$anova %>% round(2)
  obj_sGMV = resi_obj_sGMV$anova %>% round(2)
  obj_WMV = resi_obj_WMV$anova %>% round(2)

  list_GMV$`CS-RESI`[i] = paste0(obj_GMV["psycho", "RESI"], " (", obj_GMV["psycho", "2.5%"], ", ", obj_GMV["psycho", "97.5%"], ")")
  list_sGMV$`CS-RESI`[i] = paste0(obj_sGMV["psycho", "RESI"], " (", obj_sGMV["psycho", "2.5%"], ", ", obj_sGMV["psycho", "97.5%"], ")")
  list_WMV$`CS-RESI`[i] = paste0(obj_WMV["psycho", "RESI"], " (", obj_WMV["psycho", "2.5%"], ", ", obj_WMV["psycho", "97.5%"], ")")
  }
}
list_GMV
```
