---
title: "Table S8 - Increased ES and SD under resampling schemes in ADNI"
author: "Kaidi Kang"
date: "2023-05-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Tab. S8: Increased ES and SD under resampling schemes in ADNI
```{r}
# ADNI
## PART A
tab_data <- readRDS("~/RESI/longitudinal/data_analysis/resampling_schemes/ADNI_UKB/resamp_scheme_ADNI_21Apr2023_actual_N.rds")
tab_data = tab_data[order(tab_data$btwn_scheme, tab_data$within_scheme), ]

tab_data %<>% round(2)
tab_data$`CS RESI (95% CI)` = paste0(tab_data$mean_CS_RESI_age, " (", tab_data$CS_RESI_age_ll, ", ", tab_data$CS_RESI_age_ul, ")")
tab_data$`long RESI (95% CI)` = paste0(tab_data$mean_long_RESI_age, " (", tab_data$long_RESI_age_ll, ", ", tab_data$long_RESI_age_ul, ")")

tab_data$`btwn-subj age SD (95% CI)` = paste0(tab_data$mean_btwn_sd_age, " (", tab_data$btwn_sd_age_ll, ", ", tab_data$btwn_sd_age_ul, ")")
tab_data$`within-subj age SD (95% CI)` = paste0(tab_data$mean_within_sd_age, " (", tab_data$within_sd_age_ll, ", ", tab_data$within_sd_age_ul, ")")

part_ADNI = tab_data[, c("btwn_scheme", "within_scheme",  "btwn-subj age SD (95% CI)", "within-subj age SD (95% CI)", "CS RESI (95% CI)", "long RESI (95% CI)")]
rownames(part_ADNI) = NULL
print(part_ADNI %>% t() %>% as.data.frame)

```

```{r}
cat("The increase in % between-subject SD of age across between-subject schemes and under within-subject scheme 0: \n")
temp = subset(tab_data, within_scheme == 0)
paste0(round((temp$mean_btwn_sd_age - temp$mean_btwn_sd_age[1])/ temp$mean_btwn_sd_age[1] * 100, 2), " %")

cat("The increase in % CS-RESI of age across between-subject schemes and under within-subject scheme 0: \n")
paste0(round((temp$mean_CS_RESI_age - temp$mean_CS_RESI_age[1])/ temp$mean_CS_RESI_age[1] * 100, 2), " %")

cat("The increase in % L-RESI of age across between-subject schemes and under within-subject scheme 0: \n")
paste0(round((temp$mean_long_RESI_age - temp$mean_long_RESI_age[1])/ temp$mean_long_RESI_age[1] * 100, 2), " %")

```


```{r}
# Part B: 2 observations
tab_data <- readRDS("~/RESI/longitudinal/data_analysis/resampling_schemes/ADNI_UKB/resamp_scheme_ADNI_21Apr2023_actual_N.rds")
tab_data = tab_data[order(tab_data$btwn_scheme, tab_data$within_scheme), ]

tab_data %<>% round(2)
tab_data$`CS RESI (95% CI)` = paste0(tab_data$mean_CS_RESI_age_2obs, " (", tab_data$CS_RESI_age_2obs_ll, ", ", tab_data$CS_RESI_age_2obs_ul, ")")
tab_data$`long RESI (95% CI)` = paste0(tab_data$mean_long_RESI_age_2obs, " (", tab_data$long_RESI_age_2obs_ll, ", ", tab_data$long_RESI_age_2obs_ul, ")")

tab_data$`btwn-subj age SD (95% CI)` = paste0(tab_data$mean_btwn_sd_age_2obs, " (", tab_data$btwn_sd_age_2obs_ll, ", ", tab_data$btwn_sd_age_2obs_ul, ")")
tab_data$`within-subj age SD (95% CI)` = paste0(tab_data$mean_within_sd_age_2obs, " (", tab_data$within_sd_age_2obs_ll, ", ", tab_data$within_sd_age_2obs_ul, ")")

part_ADNI_2obs = tab_data[, c("btwn_scheme", "within_scheme",  "btwn-subj age SD (95% CI)", "within-subj age SD (95% CI)", "CS RESI (95% CI)", "long RESI (95% CI)")]
rownames(part_ADNI_2obs) = NULL
print(part_ADNI_2obs %>% t() %>% as.data.frame)
```

```{r}
# ADNI: 2-observation
cat("The increase in % between-subject SD of age across between-subject schemes and under within-subject scheme 0: \n")
temp = subset(tab_data, within_scheme == 0)
paste0(round((temp$mean_btwn_sd_age_2obs - temp$mean_btwn_sd_age_2obs[1])/ temp$mean_btwn_sd_age_2obs[1] * 100, 2), " %")

cat("The increase in % CS-RESI of age across between-subject schemes and under within-subject scheme 0: \n")
paste0(round((temp$mean_CS_RESI_age_2obs - temp$mean_CS_RESI_age_2obs[1])/ temp$mean_CS_RESI_age_2obs[1] * 100, 2), " %")

cat("The increase in % L-RESI of age across between-subject schemes and under within-subject scheme 0: \n")
paste0(round((temp$mean_long_RESI_age_2obs - temp$mean_long_RESI_age_2obs[1])/ temp$mean_long_RESI_age_2obs[1] * 100, 2), " %")

```







