---
title: "Table S2 to S6 - Meta-analyses of RESI"
author: "Kaidi Kang"
date: "2023-05-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




```{r, warning = FALSE, message = FALSE}
setwd("~/RESI/longitudinal/data_analysis")
analysis_data <- read_csv("data/analysis_data/analysis_data_combat.csv")
analysis_data %<>% as.data.frame # `tibble` will cause a lot of problems with current RESI package
study_info_clean <- read_csv("data/analysis_data/study_info_clean.csv")
study_info_clean %<>% as.data.frame

source("Code/functions/meta_analysis.R")
source("Code/functions/forest_plot.R")
```

```{r}
# GMV
ES_GMV = forest_plot(study_info = study_info_clean, outcome = "GMV", x_ul = 2)
# sGMV
ES_sGMV = forest_plot(study_info = study_info_clean, outcome = "sGMV", x_ul = 2)
# WMV
ES_WMV = forest_plot(study_info = study_info_clean, outcome = "WMV", x_ul = 2)

```

## Tab. S2: Meta-analysis of RESI for sex on GMV

```{r, results='asis'}
set.seed(2023)
meta_resi(ES = ES_GMV$ES, variable = "sex", wls = TRUE, figure = FALSE)
```


## Tab. S3: Meta-analysis of RESI for sex on sGMV
```{r, results='asis'}
set.seed(2023)
meta_resi(ES = ES_sGMV$ES, variable = "sex", wls = TRUE, figure = FALSE)
```

## Tab. S4: Meta-analysis of RESI for sex on WMV
```{r, results='asis'}
set.seed(2023)
meta_resi(ES = ES_WMV$ES, variable = "sex", wls = TRUE, figure = FALSE)
```

## Tab. S5: Meta-analysis of RESI for age on sGMV
```{r, results='asis'}
set.seed(2023)
meta_resi(ES = ES_sGMV$ES, variable = "age", wls = TRUE, figure = FALSE)
```

## Tab. S6: Meta-analysis of RESI for age on WMV
```{r, results='asis'}
set.seed(2023)
meta_resi(ES = ES_WMV$ES, variable = "age", wls = TRUE, figure = FALSE)
```