---
title: "Table 1 - Meta-analysis results"
author: "Kaidi Kang"
date: "2023-05-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning = FALSE, message = FALSE}
setwd("~/RESI/longitudinal/data_analysis")
analysis_data <- read_csv("data/analysis_data/analysis_data_combat.csv")
analysis_data %<>% as.data.frame # `tibble` will cause a lot of problems with current RESI package
study_info_clean <- read_csv("data/analysis_data/study_info_clean.csv")
study_info_clean %<>% as.data.frame

source("Code/functions/meta_analysis.R")
source("Code/functions/forest_plot.R")

```

## Table 1 (Meta-analysis)
```{r, results='asis'}
# GMV
ES_GMV = forest_plot(study_info = study_info_clean, outcome = "GMV", x_ul = 2)
# sGMV
ES_sGMV = forest_plot(study_info = study_info_clean, outcome = "sGMV", x_ul = 2)
# WMV
ES_WMV = forest_plot(study_info = study_info_clean, outcome = "WMV", x_ul = 2)


set.seed(2023)
meta_resi(ES = ES_GMV$ES, variable = "age", wls = TRUE, figure = FALSE)
```